Pathfinding::GraphUpdateObject
int addPenalty
Penalty to add to the nodes.
Referenced by GraphUpdateObject.Apply, GraphUpdateScene.Apply.
Bounds bounds
The bounds to update nodes within.
Referenced by GraphUpdateObject.GraphUpdateObject, GridGraph.UpdateArea, PointGraph.UpdateArea.
bool modifyTag
bool modifyWalkability
If true, all nodes walkable variables will be set to setWalkability.
Referenced by GraphUpdateObject.Apply, GraphUpdateScene.Apply, GridGraph.UpdateArea.
NNConstraint nnConstraint
NNConstraint to use.
The Pathfinding.NNConstraint.SuitableGraph function will be called on the NNConstraint to enable filtering of which graphs to update. As the Pathfinding.NNConstraint.SuitableGraph function is A* Pathfinding Project Pro only, this variable doesn't really affect anything in the free version. A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
bool requiresFloodFill
Performance boost.
This controlls if a flood fill will be carried out after this GUO has been applied. If you are sure that a GUO will not modify walkability or connections. You can set this to false. For example when only updating penalty values it can save processing power when setting this to false. Especially on large graphs. If you set this to false, even though it does change e.g walkability, it can lead to paths returning that they failed even though there is a path, or the try to search the whole graph for a path even though there is none, and will in the processes use wast amounts of processing power. If using the basic GraphUpdateObject (not a derived class), a quick way to check if it is going to need a flood fill is to check if modifyWalkability is true or updatePhysics is true.
Referenced by AstarPath.DoUpdateGraphs.
int setTag
bool setWalkability
If modifyWalkability is true, the nodes' walkable variable will be set to this.
Referenced by GraphUpdateObject.Apply, GraphUpdateScene.Apply.
GraphUpdateShape shape
bool trackChangedNodes
Track which nodes are changed and save backup data.
Used internally to revert changes if needed.
Referenced by GraphUpdateObject.WillUpdateNode, GraphUpdateObject.RevertFromBackup, GraphUpdateUtilities.UpdateGraphsNoBlock.
bool updatePhysics
Use physics checks to update nodes.
When updating a grid graph and this is true, the nodes' position and walkability will be updated using physics checks with settings from "Collision Testing" and "Height Testing". Also when updating a PointGraph, setting this to true will make it re-evaluate all connections in the graph which passes through the bounds. This has no effect when updating GridGraphs if modifyWalkability is turned on
Referenced by GraphUpdateScene.Apply, GridGraph.UpdateArea, PointGraph.UpdateArea.
List<ulong> backupData
List<Int3> backupPositionData
List<GraphNode> changedNodes
GraphUpdateObject()
GraphUpdateObject(Bounds b)
Creates a new GUO with the specified bounds.
References GraphUpdateObject.bounds.
virtual void Apply(GraphNode node)
Updates the specified node using this GUO's settings.
References GraphUpdateObject.addPenalty, GraphUpdateObject.modifyWalkability, GraphUpdateObject.setWalkability.
Referenced by GridGraph.UpdateArea, PointGraph.UpdateArea.
virtual void RevertFromBackup()
Reverts penalties and flags (which includes walkability) on every node which was updated using this GUO.
Data for reversion is only saved if trackChangedNodes is true
References GraphUpdateObject.trackChangedNodes.
Referenced by GraphUpdateUtilities.UpdateGraphsNoBlock.
virtual void WillUpdateNode(GraphNode node)
Should be called on every node which is updated with this GUO before it is updated.
node The node to save fields for. If null, nothing will be done trackChangedNodes
References GraphUpdateObject.trackChangedNodes, GraphNode.Flags.
Referenced by GridGraph.UpdateArea, PointGraph.UpdateArea.