Pathfinding::ModifierConverter
static bool AllBits(ModifierData a, ModifierData b)
Returns If a has all bits that b has set to true, also set to true.
static bool AnyBits(ModifierData a, ModifierData b)
Returns If a and b has any bits in common.
Referenced by ModifierConverter.Convert, ModifierConverter.CanConvert, ModifierConverter.CanConvertTo.
static bool CanConvert(ModifierData input, ModifierData output)
Returns If input can be converted to output.
References ModifierConverter.CanConvertTo, ModifierConverter.AnyBits.
Referenced by ModifierConverter.Convert.
static ModifierData CanConvertTo(ModifierData a)
Returns All data types a can be converted to.
References ModifierConverter.AnyBits.
Referenced by ModifierConverter.CanConvert.
static ModifierData Convert(Path p, ModifierData input, ModifierData output)
Converts a path from input to output.
References ModifierConverter.CanConvert, ModifierConverter.AnyBits, Path.vectorPath, Path.path.
Referenced by Seeker.RunModifiers.