RVOObstacle
ObstacleVertexWinding
Keeps agents from entering the obstacle.
ObstacleVertexWinding obstacleMode
Mode of the obstacle.
Determines winding order of the vertices
Referenced by OnDrawGizmos, AddObstacle, WindCorrectly.
Pathfinding.RVO.Simulator sim
Reference to simulator.
Referenced by OnDisable, OnEnable, Update, FindSimulator, AddObstacle, AddObstacleInternal.
ObstacleVertexWinding _obstacleMode
Last obstacle mode.
Used to check if the gizmos should be updated
Referenced by OnDrawGizmos.
List<ObstacleVertex> addedObstacles
All obstacles added.
Referenced by OnDisable, OnEnable, Start, Update, AddObstacleInternal.
bool gizmoDrawing
Enabled if currently in OnDrawGizmos.
Referenced by OnDrawGizmos, AddObstacle.
List<Vector3[]> gizmoVerts
Vertices for gizmos.
Referenced by OnDrawGizmos, AddObstacle.
Matrix4x4 prevUpdateMatrix
Last matrix the obstacle was updated with.
Used to check if the obstacle should be updated
Referenced by Start, Update.
List<Vector3[]> sourceObstacles
Original vertices for the obstacles.
Referenced by Start, Update, AddObstacleInternal.
abstract bool ExecuteInEditor
Enable executing in editor to draw gizmos.
If enabled, the CreateObstacles function will be executed in the editor as well in order to draw gizmos.
abstract bool LocalCoordinates
If enabled, all coordinates are handled as local.
Referenced by GetMatrix.
abstract bool StaticObstacle
Static or dynamic.
This determines if the obstacle can be updated by e.g moving the transform around in the scene.
void AddObstacle(Vector3[] vertices, float height)
Adds an obstacle with the specified vertices.
The vertices array might be changed by this function.
References gizmoDrawing, WindCorrectly, gizmoVerts, sim, FindSimulator, AddObstacleInternal, obstacleMode.
Referenced by RVOSquareObstacle.CreateObstacles.
abstract bool AreGizmosDirty()
Called in the editor.
This function should return true if any variables which can change the shape or position of the obstacle has changed since the last call to this function. Take a look at the RVOSquareObstacle for an example.
Referenced by OnDrawGizmos.
abstract void CreateObstacles()
Create Obstacles.
Override this and add logic for creating obstacles. You should not use the simulator's function calls directly.AddObstacle
Referenced by OnDrawGizmos, Start.
void FindSimulator()
Finds a simulator in the scene.
Saves found simulator in sim. System.InvalidOperationException When no RVOSimulator could be found.
References sim, RVOSimulator.GetSimulator.
Referenced by AddObstacle.
virtual Matrix4x4 GetMatrix()
Get's the matrix to use for vertices.
Can be overriden for custom matrices. transform.localToWorldMatrix if LocalCoordinates is true, otherwise Matrix4x4.identity
References LocalCoordinates.
Referenced by OnDrawGizmos, Start, Update, AddObstacleInternal.
void OnDisable()
Disables the obstacle.
Do not override this function
References addedObstacles, sim, Simulator.RemoveObstacle.
void OnDrawGizmos()
Draws Gizmos.
Referenced by OnDrawGizmosSelected.
void OnDrawGizmos(bool selected)
Draws Gizmos.
References gizmoDrawing, gizmoVerts, AreGizmosDirty, _obstacleMode, obstacleMode, CreateObstacles, GetMatrix.
void OnDrawGizmosSelected()
Draws Gizmos.
References OnDrawGizmos.
void OnEnable()
Enabled the obstacle.
Do not override this function
References addedObstacles, sim, Simulator.AddObstacle.
void Start()
Creates obstacles.
References addedObstacles, sourceObstacles, prevUpdateMatrix, GetMatrix, CreateObstacles.
void Update()
Updates obstacle if required.
Checks for if the obstacle should be updated (e.g if it has moved)
References GetMatrix, prevUpdateMatrix, addedObstacles, sim, Simulator.UpdateObstacle, sourceObstacles.
void AddObstacleInternal(Vector3[] vertices, float height)
Adds an obstacle.
Winding is assumed to be correct and very little error checking is done.
References addedObstacles, sim, Simulator.AddObstacle, GetMatrix, sourceObstacles.
Referenced by AddObstacle.
void WindCorrectly(Vector3[] vertices)
Winds the vertices correctly.
Winding order is determined from obstacleMode.
References obstacleMode, Polygon.IsClockwise.
Referenced by AddObstacle.