Pathfinding::RVO::Simulator
List<Agent> agents
Agents in this simulation.
float deltaTime
float desiredDeltaTime
Inverse desired simulation fps.
DesiredDeltaTime
bool doCleanObstacles
bool doubleBuffering
Use Double Buffering.
DoubleBuffering
bool doUpdateObstacles
float frameDeltaTime
float [] frameTimeBuffer
int frameTimeBufferIndex
bool interpolation
Use Interpolation.
Interpolation
KDTree kdTree
KDTree for this simulation.
float lastFrame
float lastStep
List<ObstacleVertex> obstacles
Obstacles in this simulation.
float prevDeltaTime
Worker [] workers
Worker threads.
float DeltaTime
float DesiredDeltaTime
Time in seconds between each simulation step.
This is the desired delta time, the simulation will never run at a higher fps than the rate at which the Update function is called.
Referenced by RVOSimulator.Update.
float FrameDeltaTime
bool Interpolation
Use Interpolation.
If interpolation is enabled, agent positions will be interpolated on frames when no rvo calculation is done. This has a very small overhead, but usually yields much smoother looking movement.
Referenced by RVOSimulator.Update.
KDTree KDTree
KDTree for this simulation.
Used internally by the simulation. Please only read from this tree, do not rebuild it since that can interfere with the simulation. It is rebuilt when needed.
bool Multithreading
Is using multithreading.
float PrevDeltaTime
Simulator(int workers, bool doubleBuffering)
Create a new simulator.
workers Use the specified number of worker threads. When the number zero is specified, no multithreading will be used. A good number is the number of cores on the machine. doubleBuffering Use Double Buffering for calculations. Testing done with 5000 agents and 0.1 desired delta time showed that with double buffering enabled the game ran at 50 fps for most frames, dropping to 10 fps during calculation frames. But without double buffering it ran at around 10 fps all the time. This will let threads calculate while the game progresses instead of waiting for the calculations to finish. Will only have effect if using multithreading Multithreading
IAgent AddAgent(IAgent agent)
Add a previously removed agent to the simulation.
An agent can only be in one simulation at a time, any attempt to add an agent to two simulations or multiple times to the same simulation will result in an exception being thrown.RemoveAgent
References Agent.simulator.
Referenced by LightweightRVO.CreateAgents.
IAgent AddAgent(Vector3 position)
Add an agent at the specified position.
You can use the returned interface to read several parameters such as position and velocity and set for example radius and desired velocity.RemoveAgent
References Agent.simulator.
ObstacleVertex AddObstacle(ObstacleVertex v)
Adds a previously removed obstacle.
This does not check if the obstacle is already added to the simulation, so please do not add an obstacle multiple times.It is assumed that this is a valid obstacle.
Referenced by RVOObstacle.OnEnable, RVOObstacle.AddObstacleInternal.
ObstacleVertex AddObstacle(Vector3[] vertices, float height)
Adds an obstacle described by the vertices.
RemoveObstacle
ObstacleVertex AddObstacle(Vector3[] vertices, float height, Matrix4x4 matrix)
Adds an obstacle described by the vertices.
RemoveObstacle
References ObstacleVertex.next, ObstacleVertex.prev, ObstacleVertex.position, ObstacleVertex.height, Polygon.IsClockwiseMargin.
ObstacleVertex AddObstacle(Vector3 a, Vector3 b, float height)
Adds a line obstacle with a specified height.
RemoveObstacle
References ObstacleVertex.prev, ObstacleVertex.next, ObstacleVertex.position, ObstacleVertex.height.
void ClearAgents()
Removes all agents from the simulation.
Referenced by LightweightRVO.CreateAgents.
List<Agent> GetAgents()
Get a list of all agents.
This is an internal list. I'm not going to be restrictive so you may access it since it is better for performance but please do not modify it since that can cause errors in the simulation.Do not modify this list!
List<ObstacleVertex> GetObstacles()
Get a list of all obstacles.
This is a list of obstacle vertices. Each vertex is part of a doubly linked list loop forming an obstacle polygon.Do not modify this list! AddObstacle RemoveObstacle
void RemoveAgent(IAgent agent)
Removes a specified agent from this simulation.
The agent can be added again later by using AddAgent.AddAgent(IAgent) ClearAgents
References Agent.simulator.
void RemoveObstacle(ObstacleVertex v)
Removes the obstacle identified by the vertex.
This must be the same vertex as the one returned by the AddObstacle call.AddObstacle
Referenced by RVONavmesh.RemoveObstacles, RVOObstacle.OnDisable.
void Update()
Should be called once per frame.
Referenced by RVOSimulator.Update.
void UpdateObstacle(ObstacleVertex obstacle, Vector3[] vertices, Matrix4x4 matrix)
Updates the vertices of an obstacle.
obstacle Obstacle to update vertices New vertices for the obstacle, must have at least the number of vertices in the original obstacle matrix Matrix to multiply vertices with before updating obstacle The number of vertices in an obstacle cannot be changed, existing vertices can only be moved.
References ObstacleVertex.split, ObstacleVertex.next, ObstacleVertex.prev, ObstacleVertex.position, Polygon.IsClockwiseMargin.
Referenced by RVOObstacle.Update.
void UpdateObstacles()
Rebuilds the obstacle tree at next simulation frame.
Add and remove obstacle functions call this automatically.
~Simulator()
Terminates any worker threads.
void CleanObstacles()
void ScheduleCleanObstacles()