AstarPath
bool showNavGraphs
Toggle for showing the gizmo debugging for the graphs in the scene view (editor only).
Referenced by OnDrawGizmos, AstarPathEditor.DrawMainArea, RecastGraphEditor.OnSceneGUI.
bool showUnwalkableNodes
Toggle to show unwalkable nodes.
unwalkableNodeDebugSize
Referenced by OnDrawGizmos.
GraphDebugMode debugMode
The mode to use for drawing nodes in the sceneview.
Pathfinding.GraphDebugMode
float debugFloor
Low value to use for certain debugMode modes.
For example if debugMode is set to G, this value will determine when the node will be totally red. debugRoof
float debugRoof
High value to use for certain debugMode modes.
For example if debugMode is set to G, this value will determine when the node will be totally green. debugFloor
bool showSearchTree
If enabled, nodes will draw a line to their 'parent'.
This will show the search tree for the latest path. This is editor only. TodoAdd a showOnlyLastPath flag to indicate whether to draw every node or only the ones visited by the latest path.
float unwalkableNodeDebugSize
Size of the red cubes shown in place of unwalkable nodes.
showUnwalkableNodes
Referenced by DrawUnwalkableNode.
bool stepByStep
If enabled, only one node will be searched per search iteration (frame).
Used for debugging Might not apply for all path types DeprecatedProbably does not work for ANY path types
PathLog logPathResults
The amount of debugging messages.
Use less debugging to improve performance (a bit) or just to get rid of the Console spamming. Use more debugging (heavy) if you want more information about what the pathfinding is doing. InGame will display the latest path log using in game GUI.
Referenced by OnGUI, AstarLog, AstarLogError, LogPathResults, Awake, OnDestroy, CalculatePathsThreaded, Path.LogError.
float maxNearestNodeDistanceSqr
Max Nearest Node Distance Squared.
maxNearestNodeDistance
Referenced by GetNearest, NavGraph.GetNearest, NavMeshGraph.GetNearestForceBoth.
float maxNearestNodeDistance
Max Nearest Node Distance.
When searching for a nearest node, this is the limit (world units) for how far away it is allowed to be. Pathfinding.NNConstraint.constrainDistance
bool scanOnStartup
If true, all graphs will be scanned in Awake.
This does not include loading from the cache. If you disable this, you will have to call AstarPath.active.Scan () yourself to enable pathfinding, alternatively you could load a saved graph from a file.
Referenced by Awake.
bool fullGetNearestSearch
Do a full GetNearest search for all graphs.
Additinal searches will normally only be done on the graph which in the first, fast searches proved to have the closest node. With this setting on, additional searches will be done on all graphs. More technically: GetNearestForce on all graphs will be called if true, otherwise only on the one graph which's GetNearest search returned the best node. Usually faster when disabled, but higher quality searches when enabled. When using a a navmesh or recast graph, for best quality, this setting should be combined with the Pathfinding.NavMeshGraph.accurateNearestNode setting set to true. For the PointGraph this setting doesn't matter much as it has only one search mode.
Referenced by GetNearest.
bool prioritizeGraphs
Prioritize graphs.
Graphs will be prioritized based on their order in the inspector. The first graph which has a node closer than prioritizeGraphsLimit will be chosen instead of searching all graphs.
Referenced by GetNearest.
float prioritizeGraphsLimit
Distance limit for prioritizeGraphs.
prioritizeGraphs
Referenced by GetNearest.
AstarColor colorSettings
Reference to the color settings for this AstarPath object.
Color settings include for example which color the nodes should be in, in the sceneview.
Referenced by SetUpReferences.
Heuristic heuristic
The heuristic to use.
The heuristic, often referred to as 'H' is the estimated cost from a node to the target. Different heuristics affect how the path picks which one to follow from multiple possible with the same length Pathfinding.Heuristic
Referenced by Path.Reset.
float heuristicScale
The scale of the heuristic.
If a smaller value than 1 is used, the pathfinder will search more nodes (slower). If 0 is used, the pathfinding will be equal to dijkstra's algorithm. If a value larger than 1 is used the pathfinding will (usually) be faster because it expands fewer nodes, but the paths might not longer be optimal
Referenced by Path.Reset.
ThreadCount threadCount
Number of pathfinding threads to use.
Multithreading puts pathfinding in another thread, this is great for performance on 2+ core computers since the framerate will barely be affected by the pathfinding at all. But this can cause strange errors and pathfinding stopping to work if you are not carefull (that is, if you are modifying the pathfinding scripts). For basic usage (not modding the pathfinding core) it should be safe. None indicates that the pathfinding is run in the Unity thread as a coroutineAutomatic will try to adjust the number of threads to the number of cores and memory on the computer. Less than 512mb of memory or a single core computer will make it revert to using no multithreading CalculateThreadCount A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
Referenced by Awake.
float maxFrameTime
Max number of milliseconds to spend each frame for pathfinding.
At least 500 nodes will be searched each frame (if there are that many to search). When using multithreading this value is quite irrelevant, but do not set it too low since that could add upp to some overhead, 10ms will work good for multithreading
Referenced by CalculatePathsThreaded, CalculatePaths.
const int InitialBinaryHeapSize
The initial max size of the binary heap.
The binary heaps will be expanded if necessary.
bool recyclePaths
Recycle paths to reduce memory allocations.
This will put paths in a pool to be reused over and over again. If you use this, your scripts using tht paths should copy the vectorPath array and node array (if used) because when the path is recycled, those arrays will be replaced. I.e you should not get data from it using myPath.someVariable (except when you get the path callback) because 'someVariable' might be changed when the path is recycled. This feature is currently disabled because it didn't lead to much better memory management, but could seriously screw up stuff if the user was not careful.
int minAreaSize
Defines the minimum amount of nodes in an area.
If an area has less than this amount of nodes, the area will be flood filled again with the area ID 254, it shouldn't affect pathfinding in any significant way. If you want to be able to separate areas from one another for some reason (for example to do a fast check to see if a path is at all possible) you should set this variable to 0. Can be found in A* Inspector>Settings>Min Area Size
Referenced by FloodFill.
bool limitGraphUpdates
Limit graph updates.
If toggled, graph updates will be executed less often (specified by maxGraphUpdateFreq).
Referenced by UpdateGraphs.
float maxGraphUpdateFreq
How often should graphs be updated.
If limitGraphUpdates is true, this defines the minimum amount of seconds between each graph update.
Referenced by DelayedGraphUpdate, UpdateGraphs.
string [] tagNames
Stored tag names.
AstarPath.FindTagNames AstarPath.GetTagNames
Referenced by GetTagNames.
PathHandler debugPathData
NodeRunData from debugPath.
Returns null if debugPath is null
float lastScanTime
The time it took for the last call to Scan() to complete.
Used to prevent automatically rescanning the graphs too often (editor only)
Referenced by ScanLoop.
Path debugPath
The path to debug using gizmos.
This is equal to the last path which was calculated, it is used in the editor to draw debug information using gizmos.
Referenced by CalculatePathsThreaded, CalculatePaths.
string inGameDebugPath
This is the debug string from the last completed path.
Will be updated if logPathResults == PathLog.InGame
Referenced by OnGUI, LogPathResults.
int PathsCompleted
How many paths has been computed this run.
From application start. Debugging variable
Referenced by OnDestroy, CalculatePathsThreaded, CalculatePaths.
System.Int64 TotalSearchedNodes
System.Int64 TotalSearchTime
OnVoidDelegate OnDrawGizmosCallback
Used to enable gizmos in editor scripts.
Used internally by the editor, do not use this in game code
Referenced by OnDrawGizmos, OnDestroy, AstarPathEditor.OnEnable.
OnVoidDelegate OnGraphsWillBeUpdated
OnVoidDelegate OnGraphsWillBeUpdated2
OnVoidDelegate OnAwakeSettings
Called on Awake before anything else is done.
This is called at the start of the Awake call, right after active has been set, but this is the only thing that has been done. Use this when you want to set up default settings for an AstarPath component created during runtime since some settings can only be changed in Awake (such as multithreading related stuff) //CreateanewAstarPathobjectonStartandapplysomedefaultsettings publicvoidStart(){ AstarPath.OnAwakeSettings+=ApplySettings; AstarPathastar=AddComponent<AstarPath>(); } publicvoidApplySettings(){ //Unregisterfromthedelegate AstarPath.OnAwakeSettings-=ApplySettings; //ForexampleuseMultithreadingshouldnotbechangedaftertheAwakecall //sohere'stheonlyplacetosetitifyoucreatethecomponentduringruntime AstarPath.active.useMultithreading=true; }
Referenced by Awake, OnDestroy.
OnGraphDelegate OnGraphPreScan
Called for each graph before they are scanned.
Referenced by OnDestroy, ScanLoop, NavGraph.ScanGraph.
OnGraphDelegate OnGraphPostScan
Called for each graph after they have been scanned.
All other graphs might not have been scanned yet.
Referenced by OnDestroy, ScanLoop, NavGraph.ScanGraph.
OnPathDelegate OnPathPreSearch
Called for each path before searching.
Be carefull when using multithreading since this will be called from a different thread.
Referenced by OnDestroy, CalculatePathsThreaded, CalculatePaths, AlternativePath.Apply.
OnPathDelegate OnPathPostSearch
Called for each path after searching.
Be carefull when using multithreading since this will be called from a different thread.
Referenced by OnDestroy, CalculatePathsThreaded, CalculatePaths.
OnScanDelegate OnPreScan
Called before starting the scanning.
Referenced by OnDestroy, ScanLoop, NavGraph.ScanGraph.
OnScanDelegate OnPostScan
Called after scanning.
This is called before applying links, flood-filling the graphs and other post processing.
Referenced by OnDestroy, ScanLoop, NavGraph.ScanGraph, GridGraph.OnPostScan.
OnScanDelegate OnLatePostScan
Called after scanning has completed fully.
This is called as the last thing in the Scan function.
Referenced by OnDestroy, ScanLoop.
OnScanDelegate OnGraphsUpdated
Called when any graphs are updated.
Register to for example recalculate the path whenever a graph changes.
Referenced by DoUpdateGraphs, OnDestroy.
OnVoidDelegate On65KOverflow
Called when pathID overflows 65536.
The Pathfinding.CleanupPath65K will be added to the queue, and directly after, this callback will be called. This callback will be cleared every timed it is called, so if you want to register to it repeatedly, register to it directly on receiving the callback as well.
Referenced by GetNextPathID, OnDestroy.
OnVoidDelegate OnSafeCallback
Will send a callback when it is safe to update the nodes.
Register to this with RegisterSafeNodeUpdate When it is safe is defined as between the path searches. This callback will only be sent once and is nulled directly after the callback is sent. Note that these callbacks are not thread safe when using multithreading, DO NOT call any part of the Unity API from these callbacks except for Debug.Log
Referenced by OnDestroy, RegisterSafeUpdate, CalculatePaths.
OnVoidDelegate OnThreadSafeCallback
Will send a callback when it is safe to update the nodes.
Register to this with RegisterThreadSafeNodeUpdate When it is safe is defined as between the path searches. This callback will only be sent once and is nulled directly after the callback is sent. OnSafeCallback
Referenced by ForceCallThreadSafeCallbacks, FlushThreadSafeCallbacks, OnDestroy, RegisterSafeUpdate.
AstarDistribution
int ActiveThreadsCount
Number of threads currently active.
This includes the pathfinding coroutine used for non-multithreading mode.
Referenced by WaitForPath.
NavGraph [] graphs
Shortcut to Pathfinding.AstarData.graphs.
Referenced by OnDrawGizmos, FloodFill, ScanLoop, StartPath, GetNearest, AstarPathEditor.DrawMainArea, RVONavmesh.OnLatePostScan.
System.Type [] graphTypes
See Pathfinding.AstarData.
bool IsAnyGraphUpdatesQueued
Returns if any graph updates are waiting to be applied.
Referenced by FlushGraphUpdates.
bool IsUsingMultithreading
Returns whether or not multithreading is used.
System.Exception Is thrown when it could not be decided if multithreading was used or not. This should not happen if pathfinding is set up correctly. This uses info about if threads are running right now, it does not use info from the settings on the A* object.
Referenced by FlushThreadSafeCallbacks, WaitForPath, RegisterSafeUpdate.
int NumParallelThreads
Number of parallel pathfinders.
Returns the number of concurrent processes which can calculate paths at once. When using multithreading, this will be the number of threads, if not using multithreading it is always 1 (since only 1 coroutine is used). threadInfos IsUsingMultithreading
System.Version Version
The version number for the A* Pathfinding Project.
Referenced by AstarSerializer.SerializeMeta, AstarPathEditor.GetAstarEditorSettings, AstarPathEditor.CheckForUpdates.
AstarData astarData
Reference to the Pathfinding.AstarData object for this graph.
The AstarData object stores information about all graphs.
Referenced by AstarData.GetGraph, DoUpdateGraphs, Awake, DataUpdate, SetUpReferences, Initialize, OnDestroy, FloodFill, ScanLoop, NodeCountChanged, ApplyLinks, AstarPathEditor.OnEnable, AstarPathEditor.DrawMainArea, GridGraph.PostDeserialization.
const AstarDistribution Distribution
Used by the editor to guide the user to the correct place to download updates.
Referenced by AstarPathEditor.CheckForUpdates.
Stack<GraphNode> floodStack
Stack used for flood-filling the graph.
It is saved to minimize memory allocations.
Referenced by OnDestroy, FloodFill.
Queue<GraphUpdateObject> graphUpdateQueue
Stack containing all waiting graph update queries.
Add to this stack by using UpdateGraphs UpdateGraphs
Referenced by UpdateGraphs, DoUpdateGraphs, OnDestroy.
bool isScanning
Set when scanning is being done.
It will be true up until the FloodFill is done. Used to better support Graph Update Objects called for example in OnPostScan
Referenced by UpdateGraphs, DoUpdateGraphs, ScanLoop.
uint lastUniqueAreaIndex
The last area index which was used.
Used for the FloodFill function to start flood filling with an unused area. FloodFill(Node node)
Referenced by FloodFill.
bool showGraphs
Shows or hides graph inspectors.
Used internally by the editor
Referenced by AstarPathEditor.DrawMainArea.
new AstarPath active
Returns the active AstarPath object in the scene.
Referenced by AstarData.GetGraph, TrickAbortThreads, FindTagNames, OnDrawGizmos, AstarLog, AstarLogError, DoUpdateGraphs, Awake, DataUpdate, SetUpReferences, OnDestroy, WaitForPath, StartPath, CalculatePaths, GraphUpdateScene.Apply, Path.LogError, Path.Reset, GridGraphEditor.OnInspectorGUI, GridGraphEditor.OnSceneGUI, DynamicGridObstacle.UpdateGraphs, DynamicGridObstacle.OnDestroy, NavGraph.GetNearest, NavGraph.ScanGraph, GridGraph.PostDeserialization, NavMeshGraph.GetNearestForceBoth, ABPath.Prepare, RVONavmesh.OnLatePostScan, GraphUpdateUtilities.UpdateGraphsNoBlock.
readonly bool HasPro
Used by the editor to show some Pro specific stuff.
Note that setting this to true will not grant you any additional features
Referenced by AstarPathEditor.CheckForUpdates.
Stack<Path> PathPool
Stack to hold paths waiting to be recycled.
Queue<Path> pathQueue
TodoCheck scene switches
Referenced by OnDestroy, WaitForPath, StartPath, CalculatePathsThreaded, CalculatePaths.
Pathfinding.Util.LockFreeStack pathReturnStack
IEnumerator threadEnumerator
When no multithreading is used, the IEnumerator is stored here.
When no multithreading is used, a coroutine is used instead. It is not directly called with StartCoroutine but a separate function has just a while loop which increments the main IEnumerator. This is done so other functions can step the thread forward at any time, without having to wait for Unity to update it. CalculatePaths CalculatePathsHandler
Referenced by FlushThreadSafeCallbacks, WaitForPath, CalculatePathsHandler.
PathThreadInfo [] threadInfos
Holds info about each thread.
The first item will hold information about the pathfinding coroutine when not using multithreading.
Referenced by FlushThreadSafeCallbacks, Awake, DataUpdate, UpdatePathThreadInfoNodes, OnDestroy, RegisterSafeUpdate.
Thread [] threads
bool acceptNewPaths
Disables or enables new paths to be added to the queue.
Setting this to false also makes the pathfinding thread (if using multithreading) to abort as soon as possible. It is used when OnDestroy is called to abort the pathfinding thread.
Referenced by TrickAbortThreads, WaitForPath, StartPath, CalculatePathsThreaded, CalculatePaths.
bool graphUpdateRoutineRunning
bool isRegisteredForUpdate
bool isUpdatingGraphs
float lastGraphUpdate
Time the last graph update was done.
Used to group together frequent graph updates to batches
Referenced by DelayedGraphUpdate, UpdateGraphs, DoUpdateGraphs.
ushort nextFreePathID
The next unused Path ID.
Incremented for every call to GetFromPathPool
Referenced by GetNextPathID.
Path pathReturnPop
A temporary queue for paths which weren't returned due to large processing time.
When some time limit is exceeded in ReturnPaths, paths are put on this queue until the next frame. ReturnPaths
Referenced by ReturnPaths.
bool doSetQueueState
int numActiveThreads
Number of threads currently working.
Threads are sleeping when there is no work to be done or there is a work block (such as when updating graphs)
Referenced by OnDestroy, CalculatePathsThreaded, CalculatePaths.
readonly ManualResetEvent pathQueueFlag
Flag set if there are paths to calculate.
Might get reset if a function wants to pause pathfinding (for example to update graphs)Thread flag, reset if there are no more paths in the queue
Referenced by ResetQueueStates, TrickAbortThreads, FlushThreadSafeCallbacks, RegisterSafeUpdate, StartPath, CalculatePathsThreaded.
readonly ManualResetEvent safeUpdateFlag
Thread flag, set if safe or thread safe updates need to be done.
Referenced by ResetQueueStates, RegisterSafeUpdate.
readonly System.Object safeUpdateLock
readonly ManualResetEvent threadSafeUpdateFlag
Thread flag, reset while a thread wait for the Unity thread to call threadsafe updates.
Referenced by ResetQueueStates.
bool threadSafeUpdateState
int waitForPathDepth
static void AstarLog(string s)
Logs a string while taking into account logPathResults.
References active, logPathResults.
Referenced by FloodFill, ScanLoop.
static void AstarLogError(string s)
Logs an error string while taking into account logPathResults.
References active, logPathResults.
static IEnumerator CalculatePaths(System.Object _threadInfo)
Main pathfinding function.
This function will calculate the paths in the pathfinding queue CalculatePaths
References numActiveThreads, active, maxFrameTime, acceptNewPaths, pathQueue, OnSafeCallback, Path.PrepareBase, Path.AdvanceState, OnPathPreSearch, Path.IsDone, debugPath, Path.Initialize, Path.Error, Path.duration, PathsCompleted, Path.searchedNodes, LogPathResults, OnPathPostSearch.
Referenced by CalculatePathsHandler.
static IEnumerator CalculatePathsHandler(System.Object _threadData)
Handler for the CalculatePaths function.
Will initialize an IEnumerator from the CalculatePaths function. This function has a loop which will increment the CalculatePaths function state by one every time. Supposed to be called using StartCoroutine, this enabled other functions to also increment the state of the function when needed using the threadEnumerator variable. CalculatePaths threadEnumerator
References threadEnumerator, CalculatePaths.
Referenced by Awake.
static void CalculatePathsThreaded(System.Object _threadInfo)
Main pathfinding function (multithreaded).
This function will calculate the paths in the pathfinding queue when multithreading is enabled. CalculatePaths A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
References numActiveThreads, maxFrameTime, acceptNewPaths, pathQueueFlag, pathQueue, Path.PrepareBase, Path.AdvanceState, OnPathPreSearch, Path.IsDone, debugPath, Path.Initialize, Path.Error, Path.duration, PathsCompleted, Path.searchedNodes, LogPathResults, OnPathPostSearch, logPathResults.
Referenced by Awake.
static void LockThread(System.Object _astar)
static void ResetQueueStates()
Resets all event flags.
This should be called when resetting the static members of AstarPath. OnDestroy
References pathQueueFlag, threadSafeUpdateFlag, safeUpdateFlag.
Referenced by OnDestroy.
static void TrickAbortThreads()
This will trick threads to think there is more work to be done and then abort them gracefully.
When they think there is more work to be done, they will first test if new paths should be accepted, now they are not, so the threads will abort gracefully. Only call this when you want to abort all threads. For example in the OnDestroy function. After this function has been called, it's good to loop through all threads and Thread.Join them with some timeout. If the timeout exceeds, you can call Thread.Abort on them OnDestroy acceptNewPaths
References active, acceptNewPaths, pathQueueFlag.
Referenced by OnDestroy.
static void TryCallThreadSafeCallbacks()
void ApplyLinks()
Applies links to the scanned graphs.
Called right after OnPostScan and before FloodFill().
References astarData, AstarData.userConnections, GetNearest, NNInfo.node.
Referenced by ScanLoop.
void Awake()
Sets up all needed variables and scans the graphs.
Calls Initialize, starts the ReturnPaths coroutine and scans all graphs. Also starts threads if using multithreading OnAwakeSettings
References active, OnAwakeSettings, CalculateThreadCount, threadCount, threadInfos, CalculatePathsThreaded, Initialize, ReturnsPathsHandler, scanOnStartup, astarData, AstarData.cacheStartup, AstarData.data_cachedStartup, Scan, UpdatePathThreadInfoNodes, logPathResults, CalculatePathsHandler.
void DataUpdate()
Called when a major data update has been done, makes sure everything is wired up correctly.
For example when updating number of graphs, rescanning graphs, adding or removing nodes are considered major changes. Should not be called during or before Awake has been called on the AstarPath object.
References active, astarData, AstarData.graphs, AstarData.CreateNodeRuns, threadInfos.
Referenced by AstarData.DeserializeGraphs, AstarData.DeserializeGraphsAdditive, ScanLoop.
void FloodFill(GraphNode seed)
Floodfills starting from the specified node.
References FloodFill, lastUniqueAreaIndex.
Referenced by GraphUpdateUtilities.UpdateGraphsNoBlock.
void FloodFill(GraphNode seed, uint area)
Floodfills starting from 'seed' using the specified area.
References floodStack.
void FloodFill()
Floodfills all graphs and updates areas for every node.
Pathfinding.Node.area
References astarData, AstarData.graphs, lastUniqueAreaIndex, floodStack, graphs, minAreaSize, AstarLog.
Referenced by DoUpdateGraphs, FloodFill, ScanLoop.
void FlushGraphUpdates()
Forces graph updates to run.
This will force all graph updates to run immidiately. Or rather, it will block the Unity main thread until graph updates can be performed and then issue them. This will force the pathfinding threads to finish calculate the path they are currently calculating (if any) and then pause. When all threads have paused, graph updates will be performed. Using this very often (many times per second) can reduce your fps due to a lot of threads waiting for one another. But you probably wont have to worry about that. This is almost identical to FlushThreadSafeCallbacks, but added for more descriptive name. This function will also override any time limit delays for graph updates. This is because graph updates are implemented using thread safe callbacks. So calling this function will also call other thread safe callbacks (if any are waiting). Will not do anything if there are no graph updates queued (not even call other callbacks).
References IsAnyGraphUpdatesQueued, QueueGraphUpdates, FlushThreadSafeCallbacks.
void FlushThreadSafeCallbacks()
Forces thread safe callbacks to run.
This will force all thread safe callbacks to run immidiately. Or rather, it will block the Unity main thread until callbacks can be called and then issue them. This will force the pathfinding threads to finish calculate the path they are currently calculating (if any) and then pause. When all threads have paused, thread safe callbacks will be called (which can be e.g graph updates).Using this very often (many times per second) can reduce your fps due to a lot of threads waiting for one another. But you probably wont have to worry about that This is almost (note almost) identical to FlushGraphUpdates, but added for more appropriate name.
References OnThreadSafeCallback, IsUsingMultithreading, threadInfos, threadEnumerator, pathQueueFlag.
Referenced by FlushGraphUpdates, GraphUpdateUtilities.UpdateGraphsNoBlock.
NNInfo GetNearest(Vector3 position)
Returns the nearest node to a position using the specified NNConstraint.
Searches through all graphs for their nearest nodes to the specified position and picks the closest one. Using the NNConstraint.None constraint. Pathfinding.NNConstraint
References NNConstraint.None.
Referenced by ApplyLinks, GetNearest, ABPath.Prepare.
NNInfo GetNearest(Vector3 position, NNConstraint constraint)
Returns the nearest node to a position using the specified NNConstraint.
Searches through all graphs for their nearest nodes to the specified position and picks the closest one. The NNConstraint can be used to specify constraints on which nodes can be chosen such as only picking walkable nodes. Pathfinding.NNConstraint
References GetNearest.
NNInfo GetNearest(Vector3 position, NNConstraint constraint, GraphNode hint)
Returns the nearest node to a position using the specified NNConstraint.
Searches through all graphs for their nearest nodes to the specified position and picks the closest one. The NNConstraint can be used to specify constraints on which nodes can be chosen such as only picking walkable nodes. Pathfinding.NNConstraint
References graphs, NNConstraint.None, NNConstraint.SuitableGraph, fullGetNearestSearch, NavGraph.GetNearestForce, NavGraph.GetNearest, NNInfo.node, NNInfo.clampedPosition, prioritizeGraphs, prioritizeGraphsLimit, NNInfo.constrainedNode, NNInfo.constClampedPosition, NNConstraint.Suitable, NNConstraint.constrainDistance, maxNearestNodeDistanceSqr.
GraphNode GetNearest(Ray ray)
Returns the node closest to the ray (slow).
This function is brute-force and very slow, it can barely be used once per frame
References graphs.
ushort GetNextPathID()
Returns the next free path ID.
If the next free path ID overflows 65535, a cleanup operation is queued Pathfinding.CleanupPath65K
References nextFreePathID, On65KOverflow.
Referenced by Path.Reset.
string [] GetTagNames()
Returns tag names.
Makes sure that the tag names array is not null and of length 32. If it is null or not of length 32, it creates a new array and fills it with 0,1,2,3,4 etc... AstarPath.FindTagNames
References tagNames.
Referenced by FindTagNames.
void LogProfiler()
void NodeCountChanged()
Should be called whenever the total nodecount has changed for the graphs.
Recreates temporary node data for every thread.
References astarData, AstarData.CreateNodeRuns.
void OnApplicationQuit()
Terminates eventual pathfinding threads when the application quits.
void OnDestroy()
Clears up variables and other stuff, destroys graphs.
Note that when destroying an AstarPath object, all static variables such as callbacks will be cleared.
References logPathResults, TrickAbortThreads, astarData, AstarData.graphs, NavGraph.OnDestroy, ReturnPaths, floodStack, graphUpdateQueue, OnDrawGizmosCallback, OnAwakeSettings, OnGraphPreScan, OnGraphPostScan, OnPathPreSearch, OnPathPostSearch, OnPreScan, OnPostScan, OnLatePostScan, On65KOverflow, OnGraphsUpdated, OnSafeCallback, OnThreadSafeCallback, pathQueue, threadInfos, numActiveThreads, ResetQueueStates, PathsCompleted, active.
void QueueGraphUpdates()
Will apply queued graph updates as soon as possible, regardless of limitGraphUpdates.
Calling this multiple times will not create multiple callbacks. Makes sure DoUpdateGraphs is called as soon as possible. This function is useful if you are limiting graph updates, but you want a specific graph update to be applied as soon as possible regardless of the time limit. FlushGraphUpdates
References RegisterSafeUpdate, DoUpdateGraphs.
Referenced by DelayedGraphUpdate, UpdateGraphs, FlushGraphUpdates, GraphUpdateUtilities.UpdateGraphsNoBlock.
void ResetProfiler()
void ReturnPaths(bool timeSlice)
Returns all paths in the return stack.
Paths which have been processed are put in the return stack. This function will pop all items from the stack and return them to e.g the Seeker requesting them. timeSlice Do not return all paths at once if it takes a long time, instead return some and wait until the next call.
References pathReturnPop, Path.next, Path.ReturnPath, Path.AdvanceState, Path.ReleaseSilent.
Referenced by OnDestroy, WaitForPath, ReturnsPathsHandler.
IEnumerator ReturnsPathsHandler()
Coroutine to return thread safe path callbacks.
This method will infinitely loop and call ReturnPaths ReturnPaths
References ReturnPaths.
Referenced by Awake.
void Scan()
Scans all graphs.
References ScanLoop.
Referenced by Awake.
IEnumerable<Progress> ScanLoop()
Scans all graphs.
This is a IEnumerable, you can loop through it to get the progress foreach(ProgressprogressinAstarPath.active.ScanLoop()){ Debug.Log("Scanning..."+progress.description+"-"+(progress.progress*100).ToString("0")+"%"); } Scan
References graphs, isScanning, astarData, AstarData.UpdateShortcuts, OnPreScan, GraphModifier.TriggerEvent, OnGraphPreScan, Mathfx.MapTo, NavGraph.Scan, OnGraphPostScan, OnPostScan, ApplyLinks, FloodFill, DataUpdate, OnLatePostScan, lastScanTime, AstarLog.
Referenced by Scan.
void SetUpReferences()
Makes sure active is set to this object and that astarData is not null.
Also calls OnEnable for the colorSettings and initializes astarData.userConnections if it wasn't initialized before
References active, astarData, AstarData.userConnections, colorSettings, AstarColor.OnEnable.
Referenced by Initialize, AstarPathEditor.OnEnable.
void UpdateGraphs(Bounds bounds, float t)
Update all graphs within bounds after t seconds.
This function will add a GraphUpdateObject to the graphUpdateQueue. The graphs will be updated as soon as possible. Update DoUpdateGraphs
Referenced by UpdateGraphsInteral, UpdateGraphs, GraphUpdateScene.Apply, DynamicGridObstacle.OnDestroy, GraphUpdateUtilities.UpdateGraphsNoBlock.
void UpdateGraphs(GraphUpdateObject ob, float t)
Update all graphs using the GraphUpdateObject after t seconds.
This can be used to, e.g make all nodes in an area unwalkable, or set them to a higher penalty.
References UpdateGraphsInteral.
void UpdateGraphs(Bounds bounds)
Update all graphs within bounds.
This function will add a GraphUpdateObject to the graphUpdateQueue. The graphs will be updated as soon as possible.This is equivalent to UpdateGraphs (new GraphUpdateObject (bounds))FlushGraphUpdates
References UpdateGraphs.
void UpdateGraphs(GraphUpdateObject ob)
Update all graphs using the GraphUpdateObject.
This can be used to, e.g make all nodes in an area unwalkable, or set them to a higher penalty. The graphs will be updated as soon as possible (with respect to limitGraphUpdates)FlushGraphUpdates
References graphUpdateQueue, isScanning, DoUpdateGraphs, limitGraphUpdates, lastGraphUpdate, maxGraphUpdateFreq, DelayedGraphUpdate, QueueGraphUpdates.
void UpdatePathThreadInfoNodes()
Updates NodeRun data in threads.
Called by AstarData.CreateNodeRunsIf the ASTAR_SINGLE_THREAD_OPTIMIZE define is enabled this function will only do some simple error checking.AstarData.CreateNodeRuns
References threadInfos.
Referenced by AstarData.CreateNodeRuns, Awake.
bool WillBlockPath(GraphUpdateObject ob, GraphNode n1, GraphNode n2)
Will applying this GraphUpdateObject result in no possible path between n1 and n2.
Use this only with basic GraphUpdateObjects since it needs special backup logic, it probably wont work with your own specialized ones. This function is quite a lot slower than a standart Graph Update, but not so much it will slow the game down. This might return false for small areas even if it would block the path if minAreaSize is greater than zero (0). So when using this, it is recommended to set minAreaSize to 0. AstarPath.GetNearest DeprecatedUse Pathfinding.GraphUpdateUtilities.UpdateGraphsNoBlock instead
References GraphUpdateUtilities.UpdateGraphsNoBlock.
static int CalculateThreadCount(ThreadCount count)
Calculates number of threads to use.
If count is not Automatic, simply returns count casted to an int. An int specifying how many threads to use, 0 means a coroutine should be used for pathfinding instead of a separate thread. If count is set to Automatic it will return a value based on the number of processors and memory for the current system. If memory is <= 512MB or logical cores are <= 1, it will return 0. If memory is <= 1024 it will clamp threads to max 2. Otherwise it will return the number of logical cores clamped to 6.
Referenced by Awake.
static string [] FindTagNames()
Tries to find an AstarPath object and return tag names.
If an AstarPath object cannot be found, it returns an array of length 1 with an error message. AstarPath.GetTagNames
References active, GetTagNames.
static void ForceCallThreadSafeCallbacks()
Forces thread safe callbacks to be called.
This method should only be called from inside another thread safe callback to for example instantly run some graph updates. System.InvalidOperationException if any threads are detected to be active and running
References OnThreadSafeCallback.
Referenced by GraphUpdateUtilities.UpdateGraphsNoBlock.
static bool IsPathPossible(GraphNode n1, GraphNode n2)
Returns if there is a walkable path from n1 to n2.
If you are making changes to the graph, areas must first be recaculated using FloodFill() This might return true for small areas even if there is no possible path if minAreaSize is greater than zero (0). So when using this, it is recommended to set minAreaSize to 0. Only valid as long as both nodes are walkable. GetNearest DeprecatedUse Pathfinding.GraphUpdateUtilities.IsPathPossible instead
static void RegisterSafeUpdate(OnVoidDelegate callback, bool threadSafe)
Will send a callback when it is safe to update nodes.
This is defined as between the path searches. This callback will only be sent once and is nulled directly after the callback has been sent. When using more threads than one, calling this often might decrease pathfinding performance due to a lot of idling in the threads. Not performance as in it will use much CPU power, but performance as in the number of paths per second will probably go down (though your framerate might actually increase a tiny bit)You should only call this function from the main unity thread (i.e normal game code).Note that if you do not set threadSafe to true, the callback might not be called from the Unity thread, DO NOT call any part of the Unity API from those callbacks except for Debug.Log Nodenode=AstarPath.active.GetNearest(transform.position).node; AstarPath.RegisterSafeUpdate(delegate(){ node.walkable=false; },false); Nodenode=AstarPath.active.GetNearest(transform.position).node; AstarPath.RegisterSafeUpdate(delegate(){ node.position=(Int3)transform.position; },true); Note that the second example uses transform in the callback, and must thus be threadSafe.
References IsUsingMultithreading, threadInfos, pathQueueFlag, OnThreadSafeCallback, OnSafeCallback, safeUpdateFlag.
Referenced by QueueGraphUpdates, NavGraph.SafeOnDestroy, GraphUpdateUtilities.UpdateGraphsNoBlock.
static void StartPath(Path p)
Puts the Path in queue for calculation.
The callback specified when constructing the path will be called when the path has been calculated. Usually you should use the Seeker component instead of calling this function directly.
References active, Path.GetState, acceptNewPaths, Path.Error, Path.LogError, graphs, Path.errorLog, Path.Claim, pathQueue, Path.AdvanceState, pathQueueFlag.
Referenced by Seeker.StartPath.
static void WaitForPath(Path p)
Wait for the specified path to be calculated.
Normally it takes a few frames for a path to get calculated and returned. This function will ensure that the path will be calculated when this function returns and that the callback for that path has been called.Do not confuse this with Pathfinding.Path.WaitForPath. This one will halt all operations until the path has been calculated while Pathfinding.Path.WaitForPath will wait using yield until it has been calculated. If requesting a lot of paths in one go and waiting for the last one to complete, it will calculate most of the paths in the queue (only most if using multithreading, all if not using multithreading).Use this function only if you really need to. There is a point to spreading path calculations out over several frames. It smoothes out the framerate and makes sure requesting a large number of paths at the same time does not cause lag.Graph updates and other callbacks might get called during the execution of this function. When the pathfinder is shutting down. I.e in OnDestroy, this function will not do anything. p The path to wait for. The path must be started, otherwise an exception will be thrown. Exception if pathfinding is not initialized properly for this scene (most likely no AstarPath object exists) or if the path has not been started yet. Also throws an exception if critical errors ocurr such as when the pathfinding threads have crashed (which should not happen in normal cases). This prevents an infinite loop while waiting for the path. Pathfinding.Path.WaitForPath
References active, acceptNewPaths, Path.GetState, IsUsingMultithreading, ActiveThreadsCount, pathQueue, threadEnumerator, ReturnPaths.
IEnumerator DelayedGraphUpdate()
Waits a moment with updating graphs.
If limitGraphUpdates is set, we want to keep some space between them to let pathfinding threads running and then calculate all queued calls at once
References maxGraphUpdateFreq, lastGraphUpdate, QueueGraphUpdates.
Referenced by UpdateGraphs.
void DoUpdateGraphs()
Updates the graphs based on the graphUpdateQueue.
UpdateGraphs
References lastGraphUpdate, GraphModifier.TriggerEvent, graphUpdateQueue, GraphUpdateObject.requiresFloodFill, astarData, AstarData.GetUpdateableGraphs, active, AstarData.GetGraphIndex, IUpdatableGraph.UpdateArea, isScanning, FloodFill, OnGraphsUpdated.
Referenced by QueueGraphUpdates, UpdateGraphs.
bool DrawUnwalkableNode(GraphNode node)
Draws a cube at the node's position if unwalkable.
Used for gizmo drawing
References unwalkableNodeDebugSize.
Referenced by OnDrawGizmos.
void Initialize()
Initializes various variables.
Sets up references , Searches for graph types, calls Awake on astarData and on all graphsAstarData.FindGraphTypes SetUpReferences
References SetUpReferences, astarData, AstarData.FindGraphTypes, AstarData.Awake, AstarData.graphs, NavGraph.Awake.
Referenced by Awake.
void LogPathResults(Path p)
Prints path results to the log.
What it prints can be controled using logPathResults. logPathResults PathLog Pathfinding.Path.DebugString
References logPathResults, Path.error, Path.DebugString, inGameDebugPath.
Referenced by CalculatePathsThreaded, CalculatePaths.
void OnDrawGizmos()
Calls OnDrawGizmos on graph generators and also OnDrawGizmosCallback.
References active, graphs, showNavGraphs, showUnwalkableNodes, DrawUnwalkableNode, OnDrawGizmosCallback.
void OnGUI()
Draws the InGame debugging (if enabled), also shows the fps if 'L' is pressed down.
logPathResults PathLog
References logPathResults, inGameDebugPath.
void Update()
IEnumerator UpdateGraphsInteral(GraphUpdateObject ob, float t)
Update all graphs using the GraphUpdateObject after t seconds.
References UpdateGraphs.
Referenced by UpdateGraphs.