RVOSimulator
int desiredSimulatonFPS
Desired FPS for rvo simulation.
It is usually not necessary to run a crowd simulation at a very high fps. Usually 10-30 fps is enough, but can be increased for better quality. The rvo simulation will never run at a higher fps than the game
Referenced by Update.
bool doubleBuffering
Use Double Buffering.
This will only be read at Awake. Pathfinding.RVO.Simulator.DoubleBuffering
bool interpolation
Interpolate positions between simulation timesteps.
If you are using agents directly, make sure you read from the InterpolatedPosition property.
Referenced by Update.
ThreadCount workerThreads
Number of ROV worker threads.
If set to None, no multithreading will be used.
Pathfinding.RVO.Simulator simulator
Reference to the internal simulator.
Referenced by GetSimulator.
Simulator GetSimulator()
Get the internal simulator.
Will never be null
References simulator.
Referenced by RVONavmesh.OnLatePostScan, RVOObstacle.FindSimulator, Update.
void Awake()
void Update()
Update the simulation.
References desiredSimulatonFPS, GetSimulator, Simulator.DesiredDeltaTime, Simulator.Interpolation, interpolation, Simulator.Update.