RVONavmesh
float wallHeight
Height of the walls added for each obstacle edge.
If a graph contains overlapping you should set this low enough so that edges on different levels do not interfere, but high enough so that agents cannot move over them by mistake.
Referenced by AddGraphObstacles.
Simulator lastSim
Last simulator used.
Referenced by RemoveObstacles, AddGraphObstacles.
List<ObstacleVertex> obstacles
Obstacles currently added to the simulator.
Referenced by RemoveObstacles, AddGraphObstacles.
void AddGraphObstacles(Pathfinding.RVO.Simulator sim, NavGraph graph)
Adds obstacles for a graph.
References obstacles, lastSim, RemoveObstacles, Polygon.IsClockwise, wallHeight.
Referenced by OnLatePostScan.
override void OnLatePostScan()
Called at the end of the scanning procedure.
This is the absolute last thing done by Scan.This event will be called even if Script Execution Order has messed things up (see the other two scan events).
References RemoveObstacles, AstarPath.active, AstarPath.graphs, RVOSimulator.GetSimulator, AddGraphObstacles.
Referenced by OnPostCacheLoad.
override void OnPostCacheLoad()
Called after cached graphs have been loaded.
When using cached startup, this event is analogous to OnLatePostScan and implementing scripts should do roughly the same thing for both events.This event will be called even if Script Execution Order has messed things up (see the other two scan events).
References OnLatePostScan.
void RemoveObstacles()
Removes obstacles which were added with AddGraphObstacles.
References lastSim, obstacles, Simulator.RemoveObstacle.
Referenced by OnLatePostScan, AddGraphObstacles.