Pathfinding::NavGraph
byte [] _sguid
Used to store the guid value.
NavGraph.guid
AstarPath active
Reference to the AstarPath object in the scene.
Might not be entirely safe to use, it's better to use AstarPath.active
Referenced by AstarData.CreateGraph.
bool drawGizmos
bool infoScreenOpen
Used in the editor to check if the info screen is open.
Should be inside UNITY_EDITOR only #ifs but just in case anyone tries to serialize a NavGraph instance using Unity, I have left it like this as it would otherwise cause a crash when building. Version 3.0.8.1 was released because of this bug only
uint initialPenalty
Matrix4x4 matrix
A matrix for translating/rotating/scaling the graph.
Not all graph generators sets this variable though.
Referenced by GridGraphEditor.OnInspectorGUI, GridGraphEditor.OnSceneGUI, NavGraph.RelocateNodes, GridGraph.UpdateArea, GridGraph.Linecast, GridGraph.SnappedLinecast, NavMeshGraph.GenerateNodes, RecastGraph.Scan.
string name
bool open
Is the graph open in the editor
Guid guid
Used as an ID of the graph, considered to be unique.
This is Pathfinding.Util.Guid not System.Guid. A replacement for System.Guid was coded for better compatibility with iOS
Referenced by AstarData.DeserializeGraphsPartAdditive, AstarPathEditor.CheckGraphEditors.
Matrix4x4 inverseMatrix
virtual void Awake()
This will be called on the same time as Awake on the gameObject which the AstarPath script is attached to.
(remember, not in the editor) Use this for any initialization code which can't be placed in Scan
Referenced by AstarPath.Initialize.
virtual void CreateNodes(int number)
Creates a number of nodes with the correct type for the graph.
This should not set the #nodes array, only return the nodes. Called by graph generators and when deserializing a graph with nodes. Override this function if you do not use the default Pathfinding.Node class.
Referenced by NavMeshGraph.GenerateNodes, PointGraph.Scan.
virtual void DeserializeExtraInfo(byte[] bytes)
Deserializes graph type specific node data.
SerializeExtraInfo
NNInfo GetNearest(Vector3 position)
Returns the nearest node to a position using the default NNConstraint.
position The position to try to find a close node to Pathfinding.NNConstraint.None
References NNConstraint.None.
Referenced by AstarPath.GetNearest, NavGraph.GetNearest, NavGraph.GetNearestForce.
NNInfo GetNearest(Vector3 position, NNConstraint constraint)
Returns the nearest node to a position using the specified NNConstraint.
position The position to try to find a close node to constraint Can for example tell the function to try to return a walkable node. If you do not get a good node back, consider calling GetNearestForce.
References NavGraph.GetNearest.
virtual NNInfo GetNearest(Vector3 position, NNConstraint constraint, GraphNode hint)
Returns the nearest node to a position using the specified NNConstraint.
position The position to try to find a close node to hint Can be passed to enable some graph generators to find the nearest node faster. constraint Can for example tell the function to try to return a walkable node. If you do not get a good node back, consider calling GetNearestForce.
References NNConstraint.constrainDistance, AstarPath.active, AstarPath.maxNearestNodeDistanceSqr, NNConstraint.Suitable.
virtual NNInfo GetNearestForce(Vector3 position, NNConstraint constraint)
Returns the nearest node to a position using the specified constraint.
position A Vector3 constraint A NNConstraint A NNInfo. This function will only return an empty NNInfo if there is no nodes which comply with the specified constraint.
References NavGraph.GetNearest.
Referenced by AstarPath.GetNearest.
abstract void GetNodes(GraphNodeDelegateCancelable del)
bool InSearchTree(GraphNode node, Path path)
Returns if the node is in the search tree of the path.
Only guaranteed to be correct if path is the latest path calculated. Use for gizmo drawing only.
References Path.pathHandler, PathHandler.TryGetPathNode, Path.pathID.
virtual Color NodeColor(GraphNode node, PathHandler data)
virtual void OnDestroy()
Function for cleaning up references.
This will be called on the same time as OnDisable on the gameObject which the AstarPath script is attached to (remember, not in the editor) Use for any cleanup code such as cleaning up static variables which otherwise might prevent resources from being collected Use by creating a function overriding this one in a graph class, but always call base.OnDestroy () in that function.
Referenced by AstarPath.OnDestroy, AstarPathEditor.CheckGraphEditors, NavGraph.SafeOnDestroy.
virtual void OnDrawGizmos(bool drawNodes)
virtual void PostDeserialization()
Called after all deserialization has been done for all graphs.
Can be used to set up more graph data which is not serialized
virtual void RelocateNodes(Matrix4x4 oldMatrix, Matrix4x4 newMatrix)
Relocates the nodes in this graph.
Assumes the nodes are translated using the "oldMatrix", then translates them according to the "newMatrix". The "oldMatrix" is not required by all implementations of this function though (e.g the NavMesh generator). BugDoes not always work for Grid Graphs, see http://www.arongranberg.com/forums/topic/relocate-nodes-fix/The default implementation assumes the graph is using nodes which implement the IPositionedNode interface Custom graphs which do not use such a node type must implement an override to this function (possibly throwing a NotSupportedException)
References NavGraph.matrix.
void SafeOnDestroy()
SafeOnDestroy should be used when there is a risk that the pathfinding is searching through this graph when called.
References AstarPath.RegisterSafeUpdate, NavGraph.OnDestroy.
Referenced by AstarData.RemoveGraph.
abstract void Scan()
Scans the graph, called from AstarPath.Scan Override this function to implement custom scanning logic
Referenced by AstarPath.ScanLoop, NavGraph.ScanGraph.
void ScanGraph()
Consider using AstarPath.Scan () instead since this function might screw things up if there is more than one graph.
This function does not perform all necessary postprocessing for the graph to work with pathfinding (e.g flood fill). See the source of the AstarPath.Scan function to see how it can be used.In almost all cases you should use AstarPath.Scan instead.
References AstarPath.OnPreScan, AstarPath.active, AstarPath.OnGraphPreScan, NavGraph.Scan, AstarPath.OnGraphPostScan, AstarPath.OnPostScan.
virtual byte [] SerializeExtraInfo()
Serializes graph type specific node data.
This function can be overriden to serialize extra node information (or graph information for that matter) which cannot be serialized using the standard serialization. Serialize the data in any way you want and return a byte array. When loading, the exact same byte array will be passed to the DeserializeExtraInfo function. These functions will only be called if node serialization is enabled. If null is returned from this function, the DeserializeExtraInfo function will not be called on load.