Seeker
ModifierPass
bool detailedGizmos
bool drawGizmos
List<GraphNode> lastCompletedNodePath
List<Vector3> lastCompletedVectorPath
OnPathDelegate pathCallback
Callback for when a path is completed.
Movement scripts should register to this delegate. A temporary callback can also be set when calling StartPath, but that delegate will only be called for that path
Referenced by OnPathComplete.
OnPathDelegate postProcessOriginalPath
For anything which requires the original nodes (Node[]) (before modifiers) to work.
Referenced by RunModifiers.
OnPathDelegate postProcessPath
Anything which only modifies the positions (Vector3[])
Referenced by RunModifiers.
OnPathDelegate preProcessPath
Called before pathfinding is started.
Referenced by RunModifiers.
bool saveGetNearestHints
Saves nearest nodes for previous path to enable faster Get Nearest Node calls.
This variable basically does not a affect anything at the moment. So it is hidden in the inspector
StartEndModifier startEndModifier
int [] tagPenalties
Penalties for each tag.
Tag 0 which is the default tag, will have added a penalty of tagPenalties[0]. These should only be positive values since the A* algorithm cannot handle negative penalties. This array should always have a length of 32. Pathfinding.Path.tagPenalties
Referenced by StartPath.
TagMask traversableTags
uint lastPathID
The path ID of the last path queried.
Referenced by StartPath.
Path path
The current path.
Referenced by GetCurrentPath, IsDone, OnPathComplete, StartPath.
Path prevPath
GraphNode endHint
List<IPathModifier> modifiers
OnPathDelegate onPartialPathDelegate
OnPathDelegate onPathDelegate
GraphNode startHint
OnPathDelegate tmpPathCallback
Temporary callback only called for the current path.
This value is set by the StartPath functions
Referenced by OnPathComplete, StartPath.
void Awake()
IEnumerator DelayPathStart(Path p)
void DeregisterModifier(IPathModifier mod)
Path GetCurrentPath()
Returns path.
References path.
Path GetNewPath(Vector3 start, Vector3 end)
Returns a new path instance.
The path will be taken from the path pool if path recycling is turned on. This path can be sent to StartPath(Path,OnPathDelegate,int) with no change, but if no change is required StartPath(Vector3,Vector3,OnPathDelegate) does just that. Seekerseeker=GetComponent(typeof(Seeker))asSeeker; Pathp=seeker.GetNewPath(transform.position,transform.position+transform.forward*100); p.nnConstraint=NNConstraint.Default;
References ABPath.Construct.
Referenced by StartPath.
bool IsDone()
Is the current path done calculating.
Returns true if the current path has been returned or if the path is null.Do not confuse this with Pathfinding.Path.IsDone. They do mostly return the same value, but not always. Added in 3.0.8 Behaviour changed in 3.2
References path, Path.GetState.
Referenced by AIFollow.Repath.
void OnDestroy()
void OnDrawGizmos()
void OnMultiPathComplete(Path p)
Called once for a MultiTargetPath.
Only returns the path, does not post process. A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
References OnPathComplete.
void OnPartialPathComplete(Path p)
Called for each path in a MultiTargetPath.
Only post processes the path, does not return it. A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
References OnPathComplete.
void OnPathComplete(Path p)
Called when a path has completed.
This should have been implemented as optional parameter values, but that didn't seem to work very well with delegates (the values weren't the default ones) OnPathComplete(Path,bool,bool)
Referenced by OnPartialPathComplete, OnMultiPathComplete.
void OnPathComplete(Path p, bool runModifiers, bool sendCallbacks)
Called when a path has completed.
Will post process it and return it by calling tmpPathCallback and pathCallback
References path, Path.error, RunModifiers, Path.Claim, Path.path, Path.vectorPath, tmpPathCallback, pathCallback, Path.ReleaseSilent.
void PostProcess(Path p)
Post Processes the path.
This will run any modifiers attached to this GameObject on the path. This is identical to calling RunModifiers(ModifierPass.PostProcess, path) RunModifiers Added in 3.2
References RunModifiers.
void RegisterModifier(IPathModifier mod)
void RunModifiers(ModifierPass pass, Path p)
Runs modifiers on path p.
References preProcessPath, postProcessOriginalPath, postProcessPath, ModifierConverter.Convert.
Referenced by PostProcess, OnPathComplete, StartPath.
string StackTrace()
Path StartPath(Vector3 start, Vector3 end)
Call this function to start calculating a path.
start The start point of the path end The end point of the path
Referenced by AIPath.SearchPath, StartPath, AIFollow.Repath, AIFollow.PathToTarget.
Path StartPath(Vector3 start, Vector3 end, OnPathDelegate callback)
Call this function to start calculating a path.
start The start point of the path end The end point of the path callback The function to call when the path has been calculated callback will be called when the path has completed. Callback will not be called if the path is canceled (e.g when a new path is requested before the previous one has completed)
References StartPath.
Path StartPath(Vector3 start, Vector3 end, OnPathDelegate callback, int graphMask)
Call this function to start calculating a path.
start The start point of the path end The end point of the path callback The function to call when the path has been calculated graphMask Mask used to specify which graphs should be searched for close nodes. See Pathfinding.NNConstraint.graphMask. A* Pro Feature: This parameter does not exist or has limited functionality in the Free version of the A* Pathfinding Project callback will be called when the path has completed. Callback will not be called if the path is canceled (e.g when a new path is requested before the previous one has completed)
References GetNewPath, StartPath.
Path StartPath(Path p, OnPathDelegate callback=null, int graphMask=-1)
Call this function to start calculating a path.
p The path to start calculating callback The function to call when the path has been calculated graphMask Mask used to specify which graphs should be searched for close nodes. See Pathfinding.NNConstraint.graphMask. A* Pro Feature: This parameter does not exist or has limited functionality in the Free version of the A* Pathfinding Project callback will be called when the path has completed. Callback will not be called if the path is canceled (e.g when a new path is requested before the previous one has completed)
References Path.enabledTags, Path.tagPenalties, tagPenalties, path, Path.GetState, lastPathID, Path.pathID, Path.LogError, Path.callback, Path.nnConstraint, NNConstraint.graphMask, tmpPathCallback, RunModifiers, AstarPath.StartPath.