AIFollow
bool canMove
Can it move.
Enables or disables movement and rotation
Referenced by Stop, Resume, Update.
bool canSearch
Should paths be searched for.
Setting this to false will make the AI not search for paths anymore, can save some CPU cycles. It will check every repathRate seconds if it should start to search for paths again. It will not cancel paths which are currently being calculated
Referenced by Stop, Resume, Repath.
bool drawGizmos
float pickNextWaypointDistance
The minimum distance to a waypoint to consider it as "reached".
Referenced by Update, OnDrawGizmos.
float repathRate
How often to search for a new path.
Referenced by WaitToRepath.
float rotationSpeed
How fast the AI can turn around.
Referenced by Update.
float speed
Units per second.
Referenced by Update.
Transform target
Target to move to.
Referenced by Repath.
float targetReached
The minimum distance to the end point of a path to consider it "reached" (multiplied with pickNextWaypointDistance).
This value is multiplied with pickNextWaypointDistance before it is used. Recommended range [0...1]
Referenced by Update, OnDrawGizmos.
CharacterController controller
CharacterController which handles movement.
Referenced by Start, Update.
float lastPathSearch
NavmeshController navmeshController
NavmeshController which handles movement if not null.
Referenced by Start, Update.
Vector3 [] path
This is the path the AI is currently following.
Referenced by Reset, OnPathComplete, Update, OnDrawGizmos.
int pathIndex
Seeker seeker
Seeker component which handles pathfinding calls.
Referenced by Start, Repath, PathToTarget.
Transform tr
Transform, cached because of performance.
Referenced by Start, OnPathComplete, Update, OnDrawGizmos.
void OnDrawGizmos()
Draws helper gizmos.
Currently draws a circle around the current target point with the size showing how close the AI need to get to it for it to count as "reached".
References path, tr, pickNextWaypointDistance, targetReached.
void OnPathComplete(Path p)
Called when a path has completed it's calculation.
References WaitToRepath, Path.error, path, Path.vectorPath, Mathfx.DistancePointSegmentStrict, tr.
Referenced by Repath, PathToTarget.
void PathToTarget(Vector3 targetPoint)
Start a new path moving to targetPoint.
References seeker, Seeker.StartPath, OnPathComplete.
virtual void ReachedEndOfPath()
Called when the AI reached the end of path.
This will be called once for every path it completes, so if you have a really fast repath rate it will call this function often if when it stands on the end point.
Referenced by Update.
virtual void Repath()
Recalculates the path to target.
Queries a path request to the Seeker, the path will not be calculated instantly, but will be put on a queue and calculated as fast as possible. It will wait if the current path request by this seeker has not been completed yet. Seeker.IsDone
References seeker, target, canSearch, Seeker.IsDone, WaitToRepath, ABPath.Construct, Seeker.StartPath, OnPathComplete.
Referenced by Start, WaitToRepath.
void Reset()
Will make the AI give up it's current path and stop completely.
References path.
void Resume()
Resumes walking and path searching the AI.
Added in 3.0.8 Stop canMove canSearch
References canMove, canSearch.
void Start()
Use this for initialization.
References seeker, controller, navmeshController, tr, Repath.
void Stop()
Stops the AI.
Also stops new search queries from being made Before 3.0.8 This does not prevent new path calls from making the AI move again Resume canMove canSearch
References canMove, canSearch.
void Update()
Update is called once per frame.
References path, canMove, tr, pickNextWaypointDistance, targetReached, ReachedEndOfPath, rotationSpeed, speed, navmeshController, controller.
IEnumerator WaitToRepath()
Waits the remaining time until the AI should issue a new path request.
The remaining time is defined by Time.time - lastPathSearch
References repathRate, Repath.
Referenced by OnPathComplete, Repath.