Pathfinding::ABPath
ABPath()
Default constructor.
Do not use this. Instead use Pathfinding.PathPool<Pathfinding.Path>.GetPath() If you want to use the constructor, use this: ABPathp=newABPath(); p.Reset(); And then use a Setup() method.
static ABPath Construct(Vector3 start, Vector3 end, OnPathDelegate callback=null)
Construct a path with a start and end point.
The delegate will be called when the path has been calculated. Do not confuse it with the Seeker callback as they are sent at different times. If you are using a Seeker to start the path you can set callback to null.The constructed path object
References Path.callback.
Referenced by Seeker.GetNewPath, AIFollow.Repath.
void Setup(Vector3 start, Vector3 end, OnPathDelegate callbackDelegate)
bool calculatePartial
Calculate partial path if the target node cannot be reached.
If the target node cannot be reached, the node which was closest (given by heuristic) will be chosen as target node and a partial path will be returned. This only works if a heuristic is used (which is the default). If a partial path is found, CompleteState is set to Partial. It is not required by other path types to respect this setting
Referenced by ABPath.Reset, ABPath.Initialize, ABPath.CalculateStep.
GraphNode endHint
Hints can be set to enable faster Get Nearest Node queries.
Only applies to some graph types
Referenced by ABPath.Reset, ABPath.Prepare.
GraphNode endNode
End node of the path.
Referenced by ABPath.Reset, ABPath.Prepare, ABPath.Initialize, ABPath.CalculateStep, ABPath.ResetCosts, ABPath.DebugString.
Vector3 endPoint
Exact end point of the path.
Referenced by StartEndModifier.Apply, ABPath.UpdateStartEnd, ABPath.Reset, ABPath.Prepare, ABPath.DebugString.
Int3 hTarget
Target to use for H score calculations.
Pathfinding.Node.H
Referenced by ABPath.GetHTarget, ABPath.UpdateStartEnd, ABPath.Reset, ABPath.Prepare.
Vector3 originalEndPoint
End Point exactly as in the path request.
Referenced by StartEndModifier.Apply, ABPath.UpdateStartEnd, ABPath.Reset.
Vector3 originalStartPoint
Start Point exactly as in the path request.
Referenced by AIPath.OnPathComplete, StartEndModifier.Apply, ABPath.UpdateStartEnd, ABPath.Reset.
bool recalcStartEndCosts
Defines if start and end nodes will have their connection costs recalculated for this path.
These connection costs will be more accurate and based on the exact start point and target point, however it should not be used when connection costs are not the default ones (all build in graph generators currently generate default connection costs). Int3.costMagnitude Added in 3.0.8.3 BugDoes not do anything in 3.2 and up due to incompabilities with multithreading. Will be enabled again in later versions.
GraphNode startHint
Hints can be set to enable faster Get Nearest Node queries.
Only applies to some graph types
Referenced by ABPath.Reset, ABPath.Prepare.
Int3 startIntPoint
Start point in integer coordinates.
Referenced by ABPath.UpdateStartEnd, ABPath.Reset, ABPath.Prepare.
GraphNode startNode
Start node of the path.
Referenced by ABPath.Reset, ABPath.Prepare, ABPath.Initialize, ABPath.DebugString.
Vector3 startPoint
Exact start point of the path.
Referenced by StartEndModifier.Apply, ABPath.UpdateStartEnd, ABPath.Reset, ABPath.Prepare, ABPath.DebugString.
int [] endNodeCosts
Saved original costs for the end node.
ResetCosts
Referenced by ABPath.Reset, ABPath.ResetCosts.
bool hasEndPoint
Determines if a search for an end node should be done.
Set by different path types. Added in 3.0.8.3
Referenced by ABPath.Reset, ABPath.Prepare, ABPath.Initialize, ABPath.ResetCosts, ABPath.DebugString.
PathNode partialBestTarget
Current best target for the partial path.
This is the node with the lowest H score
Referenced by ABPath.Reset, ABPath.Initialize, ABPath.CalculateStep.
ABPath(Vector3 start, Vector3 end, OnPathDelegate callbackDelegate)
Create a new path with a start and end point.
The delegate will be called when the path has been calculated. Do not confuse it with the Seeker callback as they are sent at different times. If you are using a Seeker to start the path you can set callbackDelegate to null
References ABPath.Reset.
override void CalculateStep(long targetTick)
Calculates the path until completed or until the time has passed targetTick.
Usually a check is only done every 500 nodes if the time has passed targetTick. Time/Ticks are got from System.DateTime.UtcNow.Ticks.Basic outline of what the function does for the standard path (Pathfinding.ABPath). whiletheendhasnotbeenfoundandnoerrorhasocurred checkifwehavereachedtheend ifso,exitandreturnthepath openthecurrentnode,i.eloopthroughitsneighbours,markthemasvisitedandputthemonaheap checkiftherearestillnodeslefttoprocess(orhavewesearchedthewholegraph) iftherearenone,flagerrorandexit popthenextnodeoftheheapandsetitascurrent checkifthefunctionhasexceededthetimelimit ifso,returnandwaitforthefunctiontogetcalledagain
References Path.CompleteState, Path.searchedNodes, Path.currentR, ABPath.endNode, ABPath.partialBestTarget, GraphNode.Open, Path.pathHandler, Path.Error, Path.LogError, Path.Trace, ABPath.calculatePartial.
override string DebugString(PathLog logMode)
Returns a debug string for this path.
References Path.error, Path.duration, Path.searchedNodes, Path.path, ABPath.hasEndPoint, ABPath.endNode, Path.pathHandler, PathHandler.TryGetPathNode, ABPath.endPoint, ABPath.startPoint, ABPath.startNode, Path.errorLog, Path.pathID.
override Int3 GetHTarget()
TodoMake abstract
References ABPath.hTarget.
Vector3 GetMovementVector(Vector3 point)
Returns in which direction to move from a point on the path.
A simple and quite slow (well, compared to more optimized algorithms) algorithm first finds the closest path segment (from vectorPath) and then returns the direction to the next point from there. The direction is not normalized. Direction to move from a point, returns Vector3.zero if vectorPath is null or has a length of 0
References Path.vectorPath, Mathfx.NearestPointStrict.
override void Initialize()
Initializes the path.
Sets up the open list and adds the first node to it
References ABPath.hasEndPoint, ABPath.startNode, ABPath.endNode, Path.pathHandler, Path.Trace, Path.CompleteState, Path.pathID, GraphNode.Open, Path.searchedNodes, ABPath.partialBestTarget, ABPath.calculatePartial, Path.Error, Path.LogError, Path.currentR.
override void Prepare()
Prepares the path.
Searches for start and end nodes and does some simple checking if a path is at all possible
References Path.nnConstraint, NNConstraint.tags, Path.enabledTags, AstarPath.active, AstarPath.GetNearest, ABPath.startPoint, ABPath.startHint, PathNNConstraint.SetStart, NNInfo.node, NNInfo.clampedPosition, ABPath.startIntPoint, ABPath.startNode, ABPath.hasEndPoint, ABPath.endPoint, ABPath.endHint, ABPath.hTarget, ABPath.endNode, Path.Error, Path.LogError.
override void Reset()
Reset all values to their default values.
All inheriting path types must implement this function, resetting ALL their variables to enable recycling of paths. Call this base function in inheriting types with base.Reset ();
References ABPath.startNode, ABPath.endNode, ABPath.startHint, ABPath.endHint, ABPath.originalStartPoint, ABPath.originalEndPoint, ABPath.startPoint, ABPath.endPoint, ABPath.calculatePartial, ABPath.partialBestTarget, ABPath.hasEndPoint, ABPath.startIntPoint, ABPath.hTarget, ABPath.endNodeCosts.
Referenced by ABPath.ABPath.
void ResetCosts(Path p)
Resets End Node Costs.
Costs are updated on the end node at the start of the search to better reflect the end point passed to the path, the previous ones are saved in endNodeCosts and are reset in this function which is called after the path search is complete
References ABPath.hasEndPoint, ABPath.endNode, ABPath.endNodeCosts.
override void Recycle()
Recycle the path.
Calling this means that the path and any variables on it are not needed anymore and the path can be pooled. All path data will be reset. Implement this in inheriting path types to support recycling of paths. publicoverridevoidRecycle(){ //RecyclethePath(<Path>shouldbereplacedbythepathtypeitisimplementedin) PathPool<Path>.Recycle(this); } Do not call this function directly, instead use the Claim and Release functions. Pathfinding.PathPool Reset Claim Release
void UpdateStartEnd(Vector3 start, Vector3 end)
Sets the start and end points.
Sets originalStartPoint, originalEndPoint, startPoint, endPoint, startIntPoint and hTarget (to end )
References ABPath.originalStartPoint, ABPath.originalEndPoint, ABPath.startPoint, ABPath.endPoint, ABPath.startIntPoint, ABPath.hTarget.