Pathfinding::AstarData
AstarPath active
Shortcut to AstarPath.active.
Referenced by AstarData.CreateNodeRuns, AstarData.DeserializeGraphs, AstarData.DeserializeGraphsAdditive, AstarData.CreateGraph.
bool cacheStartup
Should graph-data be cached.
Caching the startup means saving the whole graphs, not only the settings to an internal array (data_cachedStartup) which can be loaded faster than scanning all graphs at startup. This is setup from the editor.
Referenced by AstarData.Awake, AstarPath.Awake.
bool compress
byte [] data_backup
Backup data if deserialization failed.
Referenced by AstarData.DeserializeGraphs, AstarPathEditor.DrawMainArea.
byte [] data_cachedStartup
Serialized data for cached startup.
Referenced by AstarData.Awake, AstarPath.Awake.
uint dataChecksum
NavGraph [] graphs
All graphs this instance holds.
This will be filled only after deserialization has completed
Referenced by AstarData.Awake, AstarData.SerializeGraphsPart, AstarData.DeserializeGraphsPart, AstarData.DeserializeGraphsPartAdditive, AstarData.AddGraph, AstarData.RemoveGraph, AstarData.GetGraph, AstarData.GetNode, AstarData.FindGraphOfType, AstarData.FindGraphsOfType, AstarData.GetUpdateableGraphs, AstarData.GetRaycastableGraphs, AstarData.GetGraphIndex, AstarData.GuidToIndex, AstarData.GuidToGraph, AstarPath.DataUpdate, AstarPath.Initialize, AstarPath.OnDestroy, AstarPath.FloodFill, AstarPathEditor.OnEnable, AstarPathEditor.DrawMainArea.
System.Type [] graphTypes
All supported graph types.
Populated through reflection search
Referenced by AstarData.FindGraphTypes, AstarData.GetGraphType, AstarData.CreateGraph, AstarData.AddGraph.
GridGraph gridGraph
Shortcut to the first GridGraph.
Updated at scanning time. This is the only reference to GridGraph in the core pathfinding scripts
Referenced by AstarData.UpdateShortcuts.
bool hasBeenReverted
Has the data been reverted by an undo operation.
Used by the editor's undo logic to check if the AstarData has been reverted by an undo operation and should be deserialized
NavMeshGraph navmesh
Shortcut to the first NavMeshGraph.
Updated at scanning time. This is the only reference to NavMeshGraph in the core pathfinding scripts
Referenced by AstarData.UpdateShortcuts.
PathNode [][] nodeRuns
Holds temporary path data for pathfinders.
One array for every thread. Every array is itself an array with a number of NodeRun object of which there is one per node of. These objects holds the temporary path data, such as the G and H scores and the parent node. This is separate from the static path data, e.g connections between nodes. CreateNodeRuns
PointGraph pointGraph
Shortcut to the first PointGraph.
Updated at scanning time. This is the only reference to PointGraph in the core pathfinding scripts
Referenced by AstarData.UpdateShortcuts.
byte [] revertData
UserConnection [] userConnections
Links placed by the user in the scene view.
Referenced by AstarData.Awake, AstarData.SerializeGraphsPart, AstarData.DeserializeGraphsPart, AstarData.DeserializeGraphsPartAdditive, AstarPath.SetUpReferences, AstarPath.ApplyLinks.
byte [] data
Serialized data for all graphs and settings.
Referenced by AstarData.DeserializeGraphs, AstarData.GetGraph.
NavGraph AddGraph(string type)
Adds a graph of type type to the graphs array.
References AstarData.graphTypes, AstarData.CreateGraph.
Referenced by AstarData.AddGraph.
NavGraph AddGraph(System.Type type)
Adds a graph of type type to the graphs array.
References AstarData.graphTypes, AstarData.CreateGraph, AstarData.AddGraph.
void AddGraph(NavGraph graph)
Adds the specified graph to the graphs array.
References AstarData.graphs.
void AssignNodeIndices()
void Awake()
Loads the graphs from memory, will load cached graphs if any exists.
References AstarData.userConnections, AstarData.graphs, AstarData.CreateGraph, AstarData.cacheStartup, AstarData.data_cachedStartup, AstarData.DeserializeGraphs.
Referenced by AstarPath.Initialize.
void CollectNodes(int numTemporary)
NavGraph CreateGraph(string type)
Creates a new instance of a graph of type type.
If no matching graph type was found, an error is logged and null is returned The created graph CreateGraph(System.Type)
References AstarData.graphTypes.
Referenced by AstarData.Awake, AstarData.AddGraph.
NavGraph CreateGraph(System.Type type)
Creates a new graph instance of type type.
CreateGraph(string)
References NavGraph.active, AstarData.active.
void CreateNodeRuns(int numParallel)
Creates the structure for holding temporary path data.
The data is for example the G, H and F scores and the search tree. The number of nodeRuns must be no less than the number of nodes contained in all graphs. So after adding nodes, this MUST be called. Ideally, I would code an update function which reuses most of the previous ones instead of recreating it every time. numParallel Number of parallel threads which will use the data. nodeRuns AstarPath.UpdatePathThreadInfoNodes
References AstarData.active, AstarPath.UpdatePathThreadInfoNodes.
Referenced by AstarPath.DataUpdate, AstarPath.NodeCountChanged.
void DeserializeGraphs()
Deserializes graphs from data.
References AstarData.data.
Referenced by AstarData.Awake.
void DeserializeGraphs(byte[] bytes)
Deserializes graphs from the specified byte array.
If an error ocurred, it will try to deserialize using the old deserializer. A warning will be logged if all deserializers failed.
References AstarData.DeserializeGraphsPart, AstarData.active, AstarPath.DataUpdate, AstarData.data_backup.
void DeserializeGraphsAdditive(byte[] bytes)
Deserializes graphs from the specified byte array additively.
If an error ocurred, it will try to deserialize using the old deserializer. A warning will be logged if all deserializers failed. This function will add loaded graphs to the current ones
References AstarData.DeserializeGraphsPartAdditive, AstarData.active, AstarPath.DataUpdate.
void DeserializeGraphsPart(Pathfinding.Serialization.AstarSerializer sr)
Deserializes common info.
Common info is what is shared between the editor serialization and the runtime serializer. This is mostly everything except the graph inspectors which serialize some extra data in the editor
References AstarData.graphs, AstarData.userConnections.
Referenced by AstarData.DeserializeGraphs.
void DeserializeGraphsPartAdditive(Pathfinding.Serialization.AstarSerializer sr)
Deserializes common info additively Common info is what is shared between the editor serialization and the runtime serializer.
This is mostly everything except the graph inspectors which serialize some extra data in the editor
References AstarData.graphs, AstarData.userConnections, NavGraph.guid.
Referenced by AstarData.DeserializeGraphsAdditive.
NavGraph FindGraphOfType(System.Type type)
Returns the first graph of type type found in the graphs array.
Returns null if none was found
References AstarData.graphs.
Referenced by AstarData.UpdateShortcuts.
IEnumerable FindGraphsOfType(System.Type type)
Loop through this function to get all graphs of type 'type'.
foreach(GridGraphgraphinAstarPath.astarData.FindGraphsOfType(typeof(GridGraph))){ //Dosomethingwiththegraph } AstarPath.RegisterSafeNodeUpdate
References AstarData.graphs.
void FindGraphTypes()
Find all graph types supported in this build.
Using reflection, the assembly is searched for types which inherit from NavGraph.
References AstarData.graphTypes.
Referenced by AstarPath.Initialize.
byte [] GetData()
int GetGraphIndex(NavGraph graph)
Gets the index of the NavGraph in the graphs array.
References AstarData.graphs.
Referenced by AstarPath.DoUpdateGraphs.
System.Type GetGraphType(string type)
A System.Type which matches the specified type string. If no mathing graph type was found, null is returned
References AstarData.graphTypes.
GraphNode GetNode(int graphIndex, int nodeIndex)
Returns the node at graphs[graphIndex].nodes[nodeIndex].
All kinds of error checking is done to make sure no exceptions are thrown.
References AstarData.graphs.
GraphNode GetNode(int graphIndex, int nodeIndex, NavGraph[] graphs)
Returns the node at graphs[graphIndex].nodes[nodeIndex].
The graphIndex refers to the specified graphs array. All kinds of error checking is done to make sure no exceptions are thrown
IEnumerable GetRaycastableGraphs()
All graphs which implements the UpdateableGraph interface.
foreach(IRaycastableGraphgraphinAstarPath.astarData.GetRaycastableGraphs()){ //Dosomethingwiththegraph } Pathfinding.IRaycastableGraph
References AstarData.graphs.
IEnumerable GetUpdateableGraphs()
All graphs which implements the UpdateableGraph interface.
foreach(IUpdatableGraphgraphinAstarPath.astarData.GetUpdateableGraphs()){ //Dosomethingwiththegraph } AstarPath.RegisterSafeNodeUpdate Pathfinding.IUpdatableGraph
References AstarData.graphs.
Referenced by AstarPath.DoUpdateGraphs.
NavGraph GuidToGraph(Guid guid)
Tries to find a graph with the specified GUID in the graphs array.
Returns null if none is found GuidToIndex
References AstarData.graphs.
int GuidToIndex(Guid guid)
Tries to find a graph with the specified GUID in the graphs array.
If a graph is found it returns its index, otherwise it returns -1 GuidToGraph
References AstarData.graphs.
void LoadFromCache()
void RemoveGraph(NavGraph graph)
Removes the specified graph from the graphs array and Destroys it in a safe manner.
References AstarData.graphs, NavGraph.SafeOnDestroy.
void SaveCacheData(Pathfinding.Serialization.SerializeSettings settings)
byte [] SerializeGraphs()
Serializes all graphs settings to a byte array.
DeserializeGraphs(byte[])
Referenced by AstarData.SerializeGraphs.
byte [] SerializeGraphs(Pathfinding.Serialization.SerializeSettings settings)
Main serializer function.
References AstarData.SerializeGraphs.
byte [] SerializeGraphs(Pathfinding.Serialization.SerializeSettings settings, out uint checksum)
Main serializer function.
Serializes all graphs to a byte array A similar function exists in the AstarEditor.cs script to save additional info
References AstarData.SerializeGraphsPart.
void SerializeGraphsPart(Pathfinding.Serialization.AstarSerializer sr)
Serializes common info to the serializer.
Common info is what is shared between the editor serialization and the runtime serializer. This is mostly everything except the graph inspectors which serialize some extra data in the editor
References AstarData.graphs, AstarData.userConnections.
Referenced by AstarData.SerializeGraphs.
void SetData(byte[] data, uint checksum)
void UpdateShortcuts()
Updates shortcuts to the first graph of different types.
Hard coding references to some graph types is not really a good thing imo. I want to keep it dynamic and flexible. But these references ease the use of the system, so I decided to keep them. It is the only reference to specific graph types in the pathfinding core.
References AstarData.navmesh, AstarData.FindGraphOfType, AstarData.gridGraph, AstarData.pointGraph.
Referenced by AstarPath.ScanLoop.
static NavGraph GetGraph(GraphNode node)
Returns the graph which contains the specified node.
The graph must be in the graphs array. Returns the graph which contains the node. Null if the graph wasn't found
References AstarPath.active, AstarData.data, AstarPath.astarData, AstarData.graphs.
Referenced by GridGraph.CalculateConnections, FunnelModifier.Apply.