AstarPathEditor
string alternativeEditorAssets
Alternative path to the editor assets folder for the A* Pathfinding Project.
Deprecated
bool askForDarkSkin
If the dark skin is detected, show a popup asking if the dark skin should be used.
Referenced by GetAstarEditorSettings, DrawDarkSkinDialog.
readonly string AstarProButton
string astarProInfoURL
URL to more info about the A* Pathfinding Project.
Deprecated
readonly string AstarProTooltip
Dictionary<string,string> astarServerData
Holds various URLs and text for the editor.
This info can be updated when a check for new versions is done to ensure that there are no invalid links.
GUISkin astarSkin
string CRecastHelpURL
string documentationURL
URL to the documentation of the A* Pathfinding Project.
Deprecated
GUIStyle downArrow
string DownloadLink
string editorAssets
Path to the editor assets folder for the A* Pathfinding Project.
If this path turns out to be incorrect, the script will try to find the correct path LoadStyles
Referenced by GetAstarEditorSettings, LoadStyles.
bool firstRun
GUIStyle graphBoxStyle
GUIStyle graphDeleteButtonStyle
Dictionary<string,CustomGraphEditor> graphEditorTypes
List of all graph editors available (e.g GridGraphEditor)
Referenced by DrawMainArea.
GUIStyle graphGizmoButtonStyle
GUIStyle graphInfoButtonStyle
bool hasForcedNoDarkSkin
True if the user answered No on askForDarkSkin.
Referenced by GetAstarEditorSettings, DrawDarkSkinDialog.
GUIStyle helpBox
System.Version latestAstarVersion
Latest version of the A* Pathfinding Project.
Referenced by GetAstarEditorSettings.
string latestAstarVersionDesc
Description of the latest update of the A* Pathfinding Project.
Referenced by GetAstarEditorSettings.
string latestAstarVersionURL
string ModifierHelpURL
URL to a page with more info on modifiers.
Deprecated
bool refreshedServerData
False if astarServerData has not yet been updated with latest data.
The data is got from the server on system update checks, it is cached in editor prefs.
string scriptsFolder
Pathfinding.Serialization.SerializeSettings serializationSettings
bool showSerializationSettings
bool stylesLoaded
GUIStyle thinHelpBox
GUIStyle upArrow
WWW updateCheckObject
double updateCheckRate
string updateURL
URL to the version file containing the latest version number.
Deprecated
Referenced by CheckForUpdates.
bool useDarkSkin
Toggle to use a darker skin which matches the Unity Pro dark skin.
Referenced by GetAstarEditorSettings, LoadStyles, DrawDarkSkinDialog.
Dictionary<string,DefineObject> defines
Holds defines found in script files, used for optimizations.
A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
Referenced by DrawOptimizationSettings.
GraphNode firstShiftNode
GraphEditor [] graphEditors
List of all graph editors for graphs attached.
Referenced by OnDisable, DrawMainArea.
EditorGUILayoutx GUILayoutx
AstarPath script
int selectedUserConnection
System.Type [] graphTypes
System.DateTime lastUpdateCheck
AstarPath.AstarDistribution astarDistribution
bool showAddGraphMenu
Is the 'Add New Graph' menu open.
Referenced by DrawMainArea.
System.DateTime _lastUpdateCheck
bool aboutArea
bool colorSettings
bool customAreaColorsOpen
bool editLinks
bool editorSettings
bool editTags
bool linkSettings
bool optimizationSettings
bool showSettings
static void CheckForUpdates()
Checks for updates if there was some time since last check.
Usually called from OnInspectorGUI. It must be called repeatedly to ensure that the result is processed
References UpdateCheckCompleted, updateURL, AstarPath.Version, AstarPath.HasPro, AstarPath.Distribution.
static void DiscardFirstRun()
Discards the first run window.
It will not be shown for this project again
Referenced by DrawFirstRun.
static void EditTags()
static string GetURL(string tag)
static string GetURL(string tag, string defaultURL)
static bool IsJsEnabled()
Checks if JS support is enabled.
This is done by checking if the directory 'Assets/AstarPathfindingEditor/Editor' exists
Referenced by DrawFirstRun.
static bool LoadStyles()
Loads GUISkin and sets up styles.
editorAssets True if all styles were found, false if there was an error somewhere
References editorAssets, useDarkSkin.
Referenced by OnEnable, DrawDarkSkinDialog.
static void ParseServerMessage(string result)
static void RefreshServerMessage()
static void UpdateCheckCompleted(string result)
Handles the data from the update page.
Referenced by CheckForUpdates.
void AddGraph(System.Type type)
void CheckGraphEditors(bool forceRebuild=false)
Make sure every graph has a graph editor.
References NavGraph.OnDestroy, NavGraph.guid, GraphEditorBase.target.
Referenced by OnDisable.
GraphEditor CreateGraphEditor(string graphType)
Creates a GraphEditor for a graph.
int CreateNewUserConnection(Vector3 start, Vector3 end)
Creates a link between start and end.
AstarData.userConnections
void DeserializeGraphs()
void DeserializeGraphs(byte[] bytes)
void DisableJs()
Disables JS support if it was enabled.
This is done by restructuring folders in the project
void DrawAboutArea()
void DrawColorSettings()
void DrawDarkSkinDialog()
Draws a dialog asking the user if he/she wants to use a dark skin.
References askForDarkSkin, hasForcedNoDarkSkin, useDarkSkin, LoadStyles.
Referenced by DrawMainArea.
void DrawDebugSettings()
void DrawEditorSettings()
void DrawFirstRun()
Draws the first run dialog.
Asks if the user wants to enable JS support
References IsJsEnabled, DiscardFirstRun, EnableJs.
Referenced by DrawMainArea.
bool DrawGraph(NavGraph graph, GraphEditor graphEditor)
void DrawLinkSettings()
void DrawMainArea()
Draws the main area in the inspector.
References DrawFirstRun, DrawDarkSkinDialog, AstarPath.showGraphs, AstarPath.graphs, graphEditors, showAddGraphMenu, graphEditorTypes, AstarPath.astarData, AstarData.data_backup, AstarData.graphs, DrawOptimizationSettings, AstarPath.showNavGraphs, RepaintSceneView.
void DrawOptimizationSettings()
Draws optimizations settings.
A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
References defines.
Referenced by DrawMainArea.
void DrawSerializationSettings()
void DrawSettings()
void DrawTagSettings()
void DrawUserConnections()
void DrawUserConnectionsWindow()
void EnableJs()
Enables JS support.
This is done by restructuring folders in the project
Referenced by DrawFirstRun.
void FindGraphTypes()
Searches in the current assembly for GraphEditor and NavGraph types.
Referenced by OnEnable.
void GetAstarEditorSettings()
Reads settings frome EditorPrefs.
References latestAstarVersion, AstarPath.Version, latestAstarVersionDesc, useDarkSkin, hasForcedNoDarkSkin, askForDarkSkin, editorAssets.
Referenced by OnEnable.
bool HandleUndo()
void LoadGraphs()
void OnDisable()
Cleans up editor stuff.
References CheckGraphEditors, graphEditors.
void OnDrawGizmos()
Draw Editor Gizmos in graphs.
This is called using a delegate OnDrawGizmosCallback in the AstarPath script.
Referenced by OnEnable.
void OnEnable()
Enables editor stuff.
Loads graphs, reads settings and sets everything up
References AstarPath.OnDrawGizmosCallback, OnDrawGizmos, AstarPath.SetUpReferences, FindGraphTypes, GetAstarEditorSettings, LoadStyles, AstarPath.astarData, AstarData.graphs.
override void OnInspectorGUI()
void OnSceneGUI()
void RemoveGraph(NavGraph graph)
void RepaintSceneView()
Repaints Scene View.
Uses Undocumented Unity Calls (should be safe for Unity 3.x though)
Referenced by DrawMainArea.
void SaveGraphsAndUndo(EventType et=EventType.Used)
byte [] SerializeGraphs()
byte [] SerializeGraphs(out uint checksum)
byte [] SerializeGraphs(Pathfinding.Serialization.SerializeSettings settings, out uint checksum)
void SetAstarEditorSettings()
void RemoveConnection(UserConnection conn)
Removes user connection conn from the script.astarData.userConnections array.