Pathfinding::NavMeshGraph
bool accurateNearestNode
More accurate nearest node queries.
When on, looks for the closest point on every triangle instead of if point is inside the node triangle in XZ space. This is slower, but a lot better if your mesh contains overlaps (e.g bridges over other areas of the mesh). Note that for maximum effect the Full Get Nearest Node Search setting should be toggled in A* Inspector Settings.
Referenced by NavMeshGraphEditor.OnInspectorGUI.
TriangleMeshNode [] nodes
Vector3 offset
Offset in world space.
Referenced by NavMeshGraphEditor.OnInspectorGUI.
Vector3 rotation
Rotation in degrees.
Referenced by NavMeshGraphEditor.OnInspectorGUI.
float scale
Scale of the graph.
Referenced by NavMeshGraphEditor.OnInspectorGUI.
Mesh sourceMesh
Mesh to construct navmesh from.
Referenced by NavMeshGraphEditor.OnInspectorGUI, NavMeshGraph.Scan.
int [] triangles
BBTree bbTree
TriangleMeshNode [] TriNodes
Int3 [] vertices
BBTree _bbTree
Bounding Box Tree.
Enables really fast lookups of nodes. A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
Matrix4x4 _originalMatrix
Int3 [] _vertices
Vector3 [] originalVertices
void AddPortal(GraphNode n1, GraphNode n2, List< Vector3 > left, List< Vector3 > right)
Add the portal between node n1 and n2 to the funnel corridor.
The left and right edges does not necesarily need to be the left and right edges (right can be left), they will be swapped if that is detected. But that works only as long as the edges do not switch between left and right in the middle of the path.
void BuildFunnelCorridor(List< GraphNode > path, int startIndex, int endIndex, List< Vector3 > left, List< Vector3 > right)
bool ContainsPoint(TriangleMeshNode node, Vector3 pos)
Returns if the point is inside the node in XZ space.
References Polygon.IsClockwise.
Referenced by NavMeshGraph.Linecast.
override void CreateNodes(int number)
Creates a number of nodes with the correct type for the graph.
This should not set the #nodes array, only return the nodes. Called by graph generators and when deserializing a graph with nodes. Override this function if you do not use the default Pathfinding.Node class.
override void DeserializeExtraInfo(byte[] bytes)
Deserializes graph type specific node data.
SerializeExtraInfo
void GenerateMatrix()
override NNInfo GetNearest(Vector3 position, NNConstraint constraint, GraphNode hint)
Returns the nearest node to a position using the specified NNConstraint.
position The position to try to find a close node to hint Can be passed to enable some graph generators to find the nearest node faster. constraint Can for example tell the function to try to return a walkable node. If you do not get a good node back, consider calling GetNearestForce.
override NNInfo GetNearestForce(Vector3 position, NNConstraint constraint)
This performs a linear search through all polygons returning the closest one.
This is usually only called in the Free version of the A* Pathfinding Project since the Pro one supports BBTrees and will do another query
Referenced by RecastGraph.GetNearestForce.
override void GetNodes(GraphNodeDelegateCancelable del)
bool Linecast(Vector3 origin, Vector3 end)
Returns if origin is visible from end on the graph.
This is not the same as Physics.Linecast, this function traverses the graph and looks for collisions instead of checking for collider intersection. A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
References NNConstraint.None, NNInfo.node.
Referenced by NavMeshGraph.Linecast.
bool Linecast(Vector3 origin, Vector3 end, GraphNode hint, out GraphHitInfo hit)
Returns if origin is visible from end on the graph.
origin Point to linecast from end Point to linecast to hit Contains info on what was hit, see GraphHitInfo hint You need to pass the node closest to the start point This is not the same as Physics.Linecast, this function traverses the graph and looks for collisions instead of checking for collider intersection. A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
References NavMeshGraph.Linecast.
bool Linecast(Vector3 origin, Vector3 end, GraphNode hint)
Returns if end is visible from origin on the graph.
origin Point to linecast from end Point to linecast to hint You need to pass the node closest to the start point This is not the same as Physics.Linecast, this function traverses the graph and looks for collisions instead of checking for collider intersection. A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
References NavMeshGraph.Linecast.
override void OnDrawGizmos(bool drawNodes)
void PostProcess()
override void RelocateNodes(Matrix4x4 oldMatrix, Matrix4x4 newMatrix)
Relocates the nodes to match the newMatrix.
The "oldMatrix" variable can be left out in this function call (only for this graph generator) since it is not used
void Scan(string objMeshPath)
Scans the graph using the path to an .obj mesh.
References NavMeshGraph.sourceMesh, NavMeshGraph.Scan.
override void Scan()
Scans the graph, called from AstarPath.Scan Override this function to implement custom scanning logic
References NavMeshGraph.sourceMesh, NavMeshGraph.GenerateNodes.
Referenced by NavMeshGraph.Scan.
override byte [] SerializeExtraInfo()
Serializes graph type specific node data.
This function can be overriden to serialize extra node information (or graph information for that matter) which cannot be serialized using the standard serialization. Serialize the data in any way you want and return a byte array. When loading, the exact same byte array will be passed to the DeserializeExtraInfo function. These functions will only be called if node serialization is enabled. If null is returned from this function, the DeserializeExtraInfo function will not be called on load.
void Sort(Vector3[] a)
void UpdateArea(GraphUpdateObject o)
Updates an area using the specified GraphUpdateObject.
Notes to implementators. This function should (in order): Call o.WillUpdateNode on the GUO for every node it will update, it is important that this is called BEFORE any changes are made to the nodes.Update walkabilty using special settings such as the usePhysics flag used with the GridGraph.Call Apply on the GUO for every node which should be updated with the GUO.Update eventual connectivity info if appropriate (GridGraphs updates connectivity, but most other graphs don't since then the connectivity cannot be recovered later).
Referenced by RecastGraph.UpdateArea.
static void BuildFunnelCorridor(INavmesh graph, List< GraphNode > path, int startIndex, int endIndex, List< Vector3 > left, List< Vector3 > right)
static Vector3 ClosestPointOnNode(TriangleMeshNode node, Int3[] vertices, Vector3 pos)
Returns the closest point of the node.
References Polygon.ClosestPointOnTriangle.
static bool ContainsPoint(TriangleMeshNode node, Vector3 pos, Int3[] vertices)
Returns if the point is inside the node in XZ space.
References Polygon.IsClockwiseMargin.
static void DeserializeMeshNodes(INavmesh graph, GraphNode[] nodes, byte[] bytes)
static void GenerateNodes(NavGraph graph, Vector3[] vectorVertices, int[] triangles, out Vector3[] originalVertices, out Int3[] vertices)
Generates a navmesh.
Based on the supplied vertices and triangles. Memory usage is about O(n)
References NavGraph.matrix, NavGraph.CreateNodes, Polygon.IsClockwise, Polygon.IsColinear, NavMeshGraph.RebuildBBTree, Polygon.TriangleArea2.
Referenced by NavMeshGraph.Scan, RecastGraph.Scan.
static NNInfo GetNearest(INavmesh graph, GraphNode[] nodes, Vector3 position, NNConstraint constraint, bool accurateNearestNode)
static NNInfo GetNearestForce(GraphNode[] nodes, Int3[] vertices, Vector3 position, NNConstraint constraint, bool accurateNearestNode)
This performs a linear search through all polygons returning the closest one.
References NavMeshGraph.GetNearestForceBoth, NNInfo.node, NNInfo.constrainedNode, NNInfo.clampedPosition, NNInfo.constClampedPosition.
static NNInfo GetNearestForceBoth(GraphNode[] nodes, Int3[] vertices, Vector3 position, NNConstraint constraint, bool accurateNearestNode)
This performs a linear search through all polygons returning the closest one.
This will fill the NNInfo with .node for the closest node not necessarily complying with the NNConstraint, and .constrainedNode with the closest node complying with the NNConstraint. GetNearestForce(Node[],Int3[],Vector3,NNConstraint,bool)
References NNConstraint.constrainDistance, AstarPath.active, AstarPath.maxNearestNodeDistanceSqr, Polygon.ClosestPointOnTriangle, NNConstraint.Suitable, Polygon.IsClockwise, NNInfo.node, NNInfo.clampedPosition, NNInfo.constrainedNode, NNInfo.constClampedPosition.
Referenced by NavMeshGraph.GetNearestForce.
static bool Linecast(INavmesh graph, Vector3 tmp_origin, Vector3 tmp_end, GraphNode hint, bool thick, float thickness, out GraphHitInfo hit)
Returns if _b is visible from _a on the graph.
graph The graph to perform the search on tmp_origin Point to start from tmp_end Point to linecast to hit Contains info on what was hit, see GraphHitInfo hint You need to pass the node closest to the start point thick An experimental feature can be enabled to use thick linecasts, does not always work as expected thickness Thickness of the thick linecast This is not the same as Physics.Linecast, this function traverses the graph and looks for collisions instead of checking for collider intersection. A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
References Int3.Precision, NavMeshGraph.ContainsPoint, Int3.ToString, Polygon.TriangleArea2, Polygon.IntersectionFactor, Int3.magnitude.
static void RebuildBBTree(NavGraph graph)
Rebuilds the BBTree on a NavGraph.
A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here NavMeshGraph.bbTree
References INavmesh.bbTree.
Referenced by NavMeshGraph.GenerateNodes.
static byte [] SerializeMeshNodes(INavmesh graph, GraphNode[] nodes)
static void UpdateArea(GraphUpdateObject o, NavGraph graph)