GraphUpdateScene
bool applyOnScan
Apply this graph update object whenever a graph is rescanned.
Referenced by OnPostScan, Apply.
bool applyOnStart
Apply this graph update object on start.
Referenced by Start.
bool convex
Use the convex hull (XZ space) of the points.
Referenced by RecalcConvex, Apply, OnDrawGizmos.
bool lockToY
Lock all points to Y = lockToYValue.
float lockToYValue
if lockToY is enabled lock all points to this value
Referenced by LockToY.
float minBoundsHeight
Minumum height of the bounds of the resulting Graph Update Object.
Useful when all points are laid out on a plane but you still need a bounds with a height greater than zero since a zero height graph update object would usually result in no nodes being updated.
Referenced by Apply.
bool modifyTag
If enabled, set all nodes' tags to setTag.
Referenced by Apply.
bool modifyWalkability
Set to true to set all targeted nodese walkability to setWalkability.
Referenced by Apply.
int penaltyDelta
Penalty to add to nodes.
Be careful when setting negative values since if a node get's a negative penalty it will underflow and instead get really large. In most cases a warning will be logged if that happens.
Referenced by InvertSettings, Apply.
Vector3 [] points
Points which define the region to update.
Referenced by RecalcConvex, ToggleUseWorldSpace, LockToY, Apply, OnDrawGizmos.
int setTag
If modifyTag is enabled, set all nodes' tags to this value.
Referenced by InvertSettings, Apply.
bool setWalkability
See modifyWalkability.
Referenced by InvertSettings, Apply.
bool updatePhysics
Update node's walkability and connectivity using physics functions.
For grid graphs, this will update the node's position and walkability exactly like when doing a scan of the graph. If enabled for grid graphs, modifyWalkability will be ignored.For Point Graphs, this will recalculate all connections which passes through the bounds of the resulting Graph Update Object using raycasts (if enabled).
Referenced by Apply.
bool useWorldSpace
Use world space for coordinates.
If true, the shape will not follow when moving around the transform
Referenced by ToggleUseWorldSpace, Apply, OnDrawGizmos.
Vector3 [] convexPoints
Private cached convex hull of the points.
Referenced by RecalcConvex, OnDrawGizmos.
bool firstApplied
Has apply been called yet.
Used to prevent applying twice when both applyOnScan and applyOnStart are enabled
Referenced by Start, Apply.
int setTagInvert
Private cached inversion of setTag.
Used for InvertSettings()
Referenced by InvertSettings.
void Apply(AstarPath active)
Apply the update.
Will only do anything if applyOnScan is enabled
References applyOnScan, Apply.
void Apply()
Updates graphs with a created GUO.
Creates a Pathfinding.GraphUpdateObject with a Pathfinding.GraphUpdateShape representing the polygon of this object and update all graphs using AstarPath.UpdateGraphs. This will not update graphs directly. See AstarPath.UpdateGraph for more info.
References AstarPath.active, firstApplied, convex, points, useWorldSpace, minBoundsHeight, GraphUpdateObject.modifyWalkability, modifyWalkability, GraphUpdateObject.setWalkability, setWalkability, GraphUpdateObject.addPenalty, penaltyDelta, GraphUpdateObject.updatePhysics, updatePhysics, modifyTag, setTag, AstarPath.UpdateGraphs.
Referenced by Start, OnPostScan, Apply.
virtual void InvertSettings()
Inverts all invertable settings for this GUS.
Namely: penalty delta, walkability, tags.Penalty delta will be changed to negative penalty delta. setWalkability will be inverted. setTag will be stored in a private variable, and the new value will be 0. When calling this function again, the saved value will be the new value.Calling this function an even number of times without changing any settings in between will be identical to no change in settings.
References setWalkability, penaltyDelta, setTagInvert, setTag.
void LockToY()
Lock all points to a specific Y value.
lockToYValue
References points, lockToYValue.
void OnDrawGizmos()
Draws some gizmos.
Referenced by OnDrawGizmosSelected.
void OnDrawGizmos(bool selected)
Draws some gizmos.
References points, useWorldSpace, convex, convexPoints, RecalcConvex.
void OnDrawGizmosSelected()
Draws some gizmos.
References OnDrawGizmos.
override void OnPostScan()
Called right after all graphs have been scanned.
FloodFill and other post processing has not been done.Since OnEnable and Awake are called roughly in the same time, the only way to ensure that these scripts get this call when scanning in Awake is to set the Script Execution Order for AstarPath to some time later than default time (see Edit -> Project Settings -> Script Execution Order). OnLatePostScan
References applyOnScan, Apply.
void RecalcConvex()
Recalculate convex points.
Will not do anything if not convex is enabled
References convex, convexPoints, Polygon.ConvexHull, points.
Referenced by OnDrawGizmos.
void Start()
Do some stuff at start.
References firstApplied, applyOnStart, Apply.
void ToggleUseWorldSpace()
Switches between using world space and not using local space.
Changes point coordinates to stay the same in world space after the change.useWorldSpace
References useWorldSpace, points.