Pathfinding::Path
OnPathDelegate callback
Callback to call when the path is complete.
This is usually sent to the Seeker component which post processes the path and then calls a callback to the script which requested the path
Referenced by Seeker.StartPath, Path.Reset, Path.ReturnPath, ABPath.Construct.
System.DateTime callTime
When the call was made to start the pathfinding for this path.
Referenced by Path.Reset.
float duration
The duration of this path in ms.
How long it took to calculate the path The number of frames/iterations this path has executed. This is the number of frames when not using multithreading. When using multithreading, this value is quite irrelevant
Referenced by AstarPath.CalculatePathsThreaded, AstarPath.CalculatePaths, Path.Reset, Path.DebugString, ABPath.DebugString.
int enabledTags
Which graph tags are traversable.
This is a bitmask so -1 = all bits set = all tags traversable. For example, to set bit 5 to true, you would do myPath.enabledTags|=1<<5; To set it to false, you would do myPath.enabledTags&=~(1<<5); The Seeker has a popup field where you can set which tags to use. If you are using a Seeker. The Seeker will set this value to what is set in the inspector field on StartPath. So you need to change the Seeker value via script, not set this value if you want to change it via script. CanTraverse
Referenced by Seeker.StartPath, Path.CanTraverse, Path.Reset, ABPath.Prepare.
int height
Height of the character.
Not used currently
Referenced by Path.Reset.
Heuristic heuristic
Determines which heuristic to use.
Referenced by Path.Reset.
float heuristicScale
Scale of the heuristic values.
Referenced by Path.Reset.
Path next
The next path to be searched.
Linked list implementation. You should never change this if you do not know what you are doing
Referenced by AstarPath.ReturnPaths, Path.Reset, LockFreeStack.Push.
NNConstraint nnConstraint
Constraint for how to search for nodes.
Referenced by Seeker.StartPath, Path.Reset, ABPath.Prepare.
List<GraphNode> path
Holds the path as a Node array.
All nodes the path traverses. This might not be the same as all nodes the smoothed path traverses.
Referenced by Seeker.OnPathComplete, Path.OnEnterPool, Path.Reset, Path.Trace, Path.DebugString, AlternativePath.Apply, FunnelModifier.Apply, ModifierConverter.Convert, StartEndModifier.Apply, ABPath.DebugString.
PathHandler pathHandler
Data for the thread calculating this path.
Referenced by Path.ErrorCheck, Path.Reset, Path.DebugString, Path.PrepareBase, NavGraph.InSearchTree, ABPath.Initialize, ABPath.CalculateStep, ABPath.DebugString.
ushort pathID
ID of this path.
Used to distinguish between different paths
Referenced by Seeker.StartPath, Path.Reset, Path.DebugString, Path.PrepareBase, NavGraph.InSearchTree, ABPath.Initialize, ABPath.DebugString.
int radius
Radius for the unit searching for the path.
Not used by any built-in pathfinders. These common name variables are put here because it is a lot faster to access fields than, for example make use of a lookup table (e.g dictionary). Or having to cast to another path type for acess.
Referenced by Path.Reset.
bool recycled
True if the path is currently recycled (i.e in the path pool).
Do not set this value. Only read. It is used internally.
Referenced by Path.ErrorCheck.
int searchedNodes
Number of nodes this path has searched.
Referenced by AstarPath.CalculatePathsThreaded, AstarPath.CalculatePaths, Path.Reset, Path.DebugString, ABPath.Initialize, ABPath.CalculateStep, ABPath.DebugString.
int searchIterations
int speed
Speed of the character.
Not used currently
Referenced by Path.Reset.
int turnRadius
Turning radius of the character.
Not used currently
Referenced by Path.Reset.
List<Vector3> vectorPath
Holds the (perhaps post processed) path as a Vector3 array.
Referenced by AIPath.CalculateVelocity, Seeker.OnPathComplete, Path.GetTotalLength, Path.OnEnterPool, Path.Reset, Path.Trace, AIFollow.OnPathComplete, AdvancedSmooth.Apply, FunnelModifier.Apply, ModifierConverter.Convert, RaycastModifier.Apply, SimpleSmoothModifier.Apply, StartEndModifier.Apply, ABPath.GetMovementVector.
int walkabilityMask
A mask for defining what type of ground a unit can traverse, not used in any default standard graph.
enabledTags Not used by any built-in pathfinders. These variables are put here because it is a lot faster to access fields than, for example make use of a lookup table (e.g dictionary)
Referenced by Path.Reset.
string _errorLog
Additional info on what went wrong.
error
Referenced by Path.LogError, Path.ForceLogError, Path.Log, Path.Reset.
GraphNode [] _path
Vector3 [] _vectorPath
List<System.Object> claimed
PathCompleteState pathCompleteState
Current state of the path.
CompleteState
Referenced by Path.Reset.
bool releasedNotSilent
PathState state
System.Object stateLock
PathCompleteState CompleteState
Current state of the path.
Referenced by Path.IsDone, Path.Error, ABPath.Initialize, ABPath.CalculateStep.
bool error
If the path failed, this is true.
errorLog
Referenced by Seeker.OnPathComplete, AstarPath.LogPathResults, Path.DebugString, AIFollow.OnPathComplete, ABPath.DebugString.
string errorLog
Log messages with info about eventual errors.
Referenced by AstarPath.StartPath, Path.DebugString, ABPath.DebugString.
int [] tagPenalties
Penalties for each tag.
Tag 0 which is the default tag, will have added a penalty of tagPenalties[0]. These should only be positive values since the A* algorithm cannot handle negative penalties. This array will never be null. If you try to set it to null or with a lenght which is not 32. It will be set to "new int[0]".If you are using a Seeker. The Seeker will set this value to what is set in the inspector field on StartPath. So you need to change the Seeker value via script, not set this value if you want to change it via script. Seeker.tagPenalties
Referenced by Seeker.StartPath, Path.Reset.
int [] _tagPenalties
Penalties for each tag.
Referenced by Path.GetTagPenalty.
PathNode currentR
The node currently being processed.
Referenced by Path.Reset, ABPath.Initialize, ABPath.CalculateStep.
bool hasBeenReset
True if the Reset function has been called.
Used to allert users when they are doing it wrong.
Referenced by Path.ErrorCheck, Path.Reset.
float maxFrameTime
The max number of milliseconds per iteration (frame, in case of non-multithreading)
void AdvanceState(PathState s)
Threadsafe increment of the state.
Referenced by AstarPath.StartPath, AstarPath.ReturnPaths, AstarPath.CalculatePathsThreaded, AstarPath.CalculatePaths.
virtual uint CalculateHScore(GraphNode node)
abstract void CalculateStep(long targetTick)
bool CanTraverse(GraphNode node)
Returns if the node can be traversed.
This per default equals to if the node is walkable and if the node's tag is included in enabledTags
References Path.enabledTags.
Referenced by PointNode.Open, GridNode.Open, TriangleMeshNode.Open, ConvexMeshNode.Open.
void Claim(System.Object o)
Claim this path.
A claim on a path will ensure that it is not recycled. If you are using a path, you will want to claim it when you first get it and then release it when you will not use it anymore. When there are no claims on the path, it will be recycled and put in a pool.Release Recycle
Referenced by AIPath.OnPathComplete, Seeker.OnPathComplete, AstarPath.StartPath, PathPool< T >.Warmup.
virtual string DebugString(PathLog logMode)
Returns a debug string for this path.
References Path.error, Path.pathHandler, Path.duration, Path.searchedNodes, Path.path, Path.errorLog, Path.pathID.
Referenced by AstarPath.LogPathResults.
void Error()
Aborts the path because of an error.
Sets error to true. This function is called when an error has ocurred (e.g a valid path could not be found). LogError
References Path.CompleteState.
Referenced by AstarPath.StartPath, AstarPath.CalculatePathsThreaded, AstarPath.CalculatePaths, Path.ForceLogError, ABPath.Prepare, ABPath.Initialize, ABPath.CalculateStep.
void ForceLogError(string msg)
Logs an error and calls Error() to true.
This is called only if something is very wrong or the user is doing something he/she really should not be doing.
References Path.Error, Path._errorLog.
Referenced by Path.PrepareBase.
virtual Int3 GetHTarget()
TodoMake abstract
PathState GetState()
Returns the state of the path in the pathfinding pipeline.
Referenced by Seeker.IsDone, Seeker.StartPath, AstarPath.WaitForPath, AstarPath.StartPath, Path.WaitForPath, Path.ErrorCheck.
uint GetTagPenalty(int tag)
Returns penalty for the given tag.
tag A value between 0 (inclusive) and 31 (inclusive).
References Path._tagPenalties.
float GetTotalLength()
Total Length of the path.
Calculates the total length of the vectorPath. Cache this rather than call this function every time since it will calculate the length every time, not just return a cached value. Total length of vectorPath, if vectorPath is null positive infinity is returned.
References Path.vectorPath.
uint GetTraversalCost(GraphNode node)
abstract void Initialize()
Initializes the path.
Sets up the open list and adds the first node to it
Referenced by AstarPath.CalculatePathsThreaded, AstarPath.CalculatePaths.
bool IsDone()
Returns if this path is done calculating.
If CompleteState is not PathCompleteState.NotCalculated. The path might not have been returned yet. Added in 3.0.8 Seeker.IsDone
References Path.CompleteState.
Referenced by AstarPath.CalculatePathsThreaded, AstarPath.CalculatePaths.
void Log(string msg)
Appends a message to the errorLog.
Nothing is logged to the console.
References Path._errorLog.
void LogError(string msg)
Appends msg to errorLog and logs msg to the console.
Debug.Log call is only made if AstarPath.logPathResults is not equal to None and not equal to InGame. Consider calling Error() along with this call.
References Path._errorLog, AstarPath.active, AstarPath.logPathResults.
Referenced by Seeker.StartPath, AstarPath.StartPath, ABPath.Prepare, ABPath.Initialize, ABPath.CalculateStep.
virtual void OnEnterPool()
Called when the path enters the pool.
This method should release e.g pooled lists and other pooled resources The base version of this method releases vectorPath and path lists. Reset() will be called after this function, not before. Do not call this function manually.
References Path.vectorPath, Path.path.
abstract void Prepare()
void PrepareBase(PathHandler pathHandler)
Prepares low level path variables for calculation.
Called before a path search will take place. Always called before the Prepare, Initialize and CalculateStep functions
References Path.pathID, PathHandler.ClearPathIDs, Path.pathHandler, Path.ErrorCheck, Path.ForceLogError.
Referenced by AstarPath.CalculatePathsThreaded, AstarPath.CalculatePaths.
void Release(System.Object o)
Releases a path claim.
Removes the claim of the path by the specified object. When the claim count reaches zero, the path will be recycled, all variables will be cleared and the path will be put in a pool to be used again. This is great for memory since less allocations are made. Claim
References Path.Recycle.
Referenced by AIPath.OnPathComplete.
void ReleaseSilent(System.Object o)
Releases the path silently.
This will remove the claim by the specified object, but the path will not be recycled if the claim count reches zero unless a Release call (not silent) has been made earlier. This is used by the internal pathfinding components such as Seeker and AstarPath so that they will not recycle paths. This enables users to skip the claim/release calls if they want without the path being recycled by the Seeker or AstarPath.
References Path.Recycle.
Referenced by Seeker.OnPathComplete, AstarPath.ReturnPaths.
virtual void Reset()
Reset all values to their default values.
All inheriting path types must implement this function, resetting ALL their variables to enable recycling of paths. Call this base function in inheriting types with base.Reset ();
References AstarPath.active, Path.hasBeenReset, Path.pathHandler, Path.callback, Path._errorLog, Path.pathCompleteState, Path.path, Path.vectorPath, Path.currentR, Path.duration, Path.searchedNodes, Path.nnConstraint, Path.next, Path.radius, Path.walkabilityMask, Path.height, Path.turnRadius, Path.speed, Path.heuristic, AstarPath.heuristic, Path.heuristicScale, AstarPath.heuristicScale, Path.pathID, Path.enabledTags, Path.tagPenalties, Path.callTime, AstarPath.GetNextPathID.
virtual void ReturnPath()
Calls callback to return the calculated path.
callback
References Path.callback.
Referenced by AstarPath.ReturnPaths.
IEnumerator WaitForPath()
Waits until this path has been calculated and returned.
Allows for very easy scripting. //InanIEnumeratorfunction Pathp=Seeker.StartPath(transform.position,transform.position+Vector3.forward*10); yieldreturnp.WaitForPath(); //Thepathiscalculatedatthisstage Do not confuse this with AstarPath.WaitForPath. This one will wait using yield until it has been calculated while AstarPath.WaitForPath will halt all operations until the path has been calculated. System.InvalidOperationException if the path is not started. Send the path to Seeker.StartPath or AstarPath.StartPath before calling this function. AstarPath.WaitForPath
References Path.GetState.
void ErrorCheck()
Does some error checking.
Makes sure the user isn't using old code paths and that no major errors have been done. An exception if any errors are found
References Path.hasBeenReset, Path.recycled, Path.pathHandler, Path.GetState.
Referenced by Path.PrepareBase.
bool HasExceededTime(int searchedNodes, long targetTime)
abstract void Recycle()
Recycle the path.
Calling this means that the path and any variables on it are not needed anymore and the path can be pooled. All path data will be reset. Implement this in inheriting path types to support recycling of paths. publicoverridevoidRecycle(){ //RecyclethePath(<Path>shouldbereplacedbythepathtypeitisimplementedin) PathPool<Path>.Recycle(this); } Do not call this function directly, instead use the Claim and Release functions. Pathfinding.PathPool Reset Claim Release
Referenced by Path.ReleaseSilent, Path.Release.
virtual void Trace(PathNode from)
Traces the calculated path from the end node to the start.
This will build an array (path) of the nodes this path will pass through and also set the vectorPath array to the path arrays positions. Assumes the vectorPath and path are empty and not null (which will be the case for a correctly initialized path).
References Path.path, Path.vectorPath.
Referenced by ABPath.Initialize, ABPath.CalculateStep.