EditorGUILayoutx
Rect fadeAreaRect
Rect lastAreaRect
Dictionary<string, FadeArea> fadeAreas
Stack<FadeArea> stack
int currentDepth
int currentIndex
GUIStyle defaultAreaStyle
GUIStyle defaultLabelStyle
Editor editor
bool fade
bool fancyEffects
bool isLayout
long lastUpdateTick
string [] layerNames
List<int> layerNumbers
List<string> layers
float speed
GUIStyle stretchStyle
GUIStyle stretchStyleThin
FadeArea BeginFadeArea(bool open, string label, string id)
FadeArea BeginFadeArea(bool open, string label, string id, GUIStyle areaStyle)
FadeArea BeginFadeArea(bool open, string label, string id, GUIStyle areaStyle, GUIStyle labelStyle)
FadeArea BeginFadeArea(bool open, string id)
FadeArea BeginFadeArea(bool open, string id, float minHeight)
FadeArea BeginFadeArea(bool open, string id, float minHeight, GUIStyle areaStyle)
bool DrawID(string id)
void EndFadeArea()
void RemoveID(string id)
static void BeginIndent()
Begin horizontal indent for the next control.
Fake "real" indent when using EditorGUIUtility.LookLikeControls. Forumula used is 13+6*EditorGUI.indentLevel
References IndentWidth.
Referenced by GridGraphEditor.IntField, GridGraphEditor.OnInspectorGUI, NavMeshGraphEditor.OnInspectorGUI, PointGraphEditor.OnInspectorGUI.
static float Berp(float start, float end, float value)
static float Coserp(float start, float end, float value)
static void EndIndent()
End indent.
Actually just a EndHorizontal call. BeginIndent
Referenced by GridGraphEditor.IntField, GridGraphEditor.OnInspectorGUI, NavMeshGraphEditor.OnInspectorGUI, PointGraphEditor.OnInspectorGUI.
static float Hermite(float start, float end, float value)
static int IndentWidth()
Returns width of current editor indent.
Unity seems to use 13+6*EditorGUI.indentLevel in U3 and 15*indent - (indent > 1 ? 2 : 0) or something like that in U4
Referenced by BeginIndent.
static LayerMask LayerMaskField(string label, LayerMask selected)
static LayerMask LayerMaskField(string label, LayerMask selected, bool showSpecial)
Displays a LayerMask field.
label Label to display showSpecial Use the Nothing and Everything selections selected Current LayerMask Unity 3.5 and up will use the EditorGUILayout.MaskField instead of a custom written one.
static void MenuCallback(System.Object ob)
static void SetTagField(GUIContent label, ref Pathfinding.TagMask value)
static float Sinerp(float start, float end, float value)
static int SingleTagField(string label, int value)
static void TagsMaskField(GUIContent changeLabel, GUIContent setLabel, ref Pathfinding.TagMask value)
static bool UnityTagMaskList(GUIContent label, bool foldout, List< string > tagMask)
static int UpDownArrows(GUIContent label, int value, GUIStyle labelStyle, GUIStyle upArrow, GUIStyle downArrow)