Pathfinding::GraphCollision
bool collisionCheck
Toggle collision check.
Referenced by GraphEditor.DrawCollisionEditor, GraphCollision.Check, GridGraph.UpdateArea.
float collisionOffset
float diameter
Diameter of capsule or sphere when checking for collision.
1 equals nodeSize . If type is set to Ray, this does not affect anything
Referenced by GraphEditor.DrawCollisionEditor, GraphCollision.Initialize, GridGraph.UpdateArea.
float fromHeight
The height to check from when checking height.
Referenced by GraphEditor.DrawCollisionEditor, GraphCollision.CheckHeight, GraphCollision.Raycast, GraphCollision.CheckHeightAll, GridGraph.UpdateNodePositionCollision.
float height
Height of capsule or length of ray when checking for collision.
If type is set to Sphere, this does not affect anything
Referenced by GraphEditor.DrawCollisionEditor, GraphCollision.Initialize, GraphCollision.Check.
bool heightCheck
Toggle height check.
If false, the grid will be flat
Referenced by GraphEditor.DrawCollisionEditor, GridGraphEditor.DrawTextureData, GraphCollision.CheckHeight, GraphCollision.Raycast, GraphCollision.CheckHeightAll, GridGraph.UpdateNodePositionCollision.
LayerMask heightMask
Layer mask to use for height check.
Referenced by GraphEditor.DrawCollisionEditor, GraphCollision.CheckHeight, GraphCollision.Raycast.
LayerMask mask
Layer mask to use for collision check.
This should only contain layers of objects defined as obstacles
Referenced by GraphEditor.DrawCollisionEditor, GraphCollision.Check.
const float RaycastErrorMargin
Offset to apply after each raycast to make sure we don't hit the same point again in CheckHeightAll.
Referenced by GraphCollision.CheckHeightAll.
RayDirection rayDirection
Direction of the ray when checking for collision.
If type is not Ray, this does not affect anything This variable is not used currently, it does not affect anything
Referenced by GraphCollision.Check.
bool thickRaycast
Toggles thick raycast.
Referenced by GraphEditor.DrawCollisionEditor, GraphCollision.CheckHeight, GraphCollision.Raycast, GraphCollision.CheckHeightAll.
float thickRaycastDiameter
Diameter of the thick raycast in nodes.
1 equals nodeSize
Referenced by GraphEditor.DrawCollisionEditor, GraphCollision.Initialize.
ColliderType type
Collision shape to use.
Pathfinding.ColliderType
Referenced by GraphEditor.DrawCollisionEditor, GraphCollision.Check.
bool unwalkableWhenNoGround
Make nodes unwalkable when no ground was found with the height raycast.
If height raycast is turned off, this doesn't affect anything.
Referenced by GraphEditor.DrawCollisionEditor, GraphCollision.CheckHeight, GraphCollision.Raycast.
Vector3 up
Direction to use as UP.
Initialize
Referenced by GraphCollision.Initialize, GraphCollision.Check, GraphCollision.CheckHeight, GraphCollision.Raycast, GraphCollision.CheckHeightAll, GridGraph.UpdateNodePositionCollision.
float finalRadius
diameter * scale * 0.5.
Where scale usually is nodeSize Initialize
Referenced by GraphCollision.Initialize, GraphCollision.Check.
float finalRaycastRadius
thickRaycastDiameter * scale * 0.5.
Where scale usually is nodeSize Initialize
Referenced by GraphCollision.Initialize, GraphCollision.CheckHeight, GraphCollision.Raycast.
Vector3 upheight
up * height.
Initialize
Referenced by GraphCollision.Initialize, GraphCollision.Check.
bool Check(Vector3 position)
Returns if the position is obstructed.
If collisionCheck is false, this will always return true.
References GraphCollision.collisionCheck, GraphCollision.up, GraphCollision.type, GraphCollision.upheight, GraphCollision.finalRadius, GraphCollision.mask, GraphCollision.rayDirection, GraphCollision.height.
Referenced by GridGraph.UpdateNodePositionCollision.
Vector3 CheckHeight(Vector3 position)
Returns the position with the correct height.
If heightCheck is false, this will return position.
Referenced by GridGraph.UpdateNodePositionCollision.
Vector3 CheckHeight(Vector3 position, out RaycastHit hit, out bool walkable)
Returns the position with the correct height.
If heightCheck is false, this will return position. walkable will be set to false if nothing was hit. The ray will check a tiny bit further than to the grids base to avoid floating point errors when the ground is exactly at the base of the grid
References GraphCollision.heightCheck, GraphCollision.thickRaycast, GraphCollision.up, GraphCollision.fromHeight, GraphCollision.finalRaycastRadius, GraphCollision.heightMask, Mathfx.NearestPoint, GraphCollision.unwalkableWhenNoGround.
RaycastHit [] CheckHeightAll(Vector3 position)
Returns all hits when checking height for position.
Does not work well with thick raycast, will only return an object a single time
References GraphCollision.heightCheck, GraphCollision.thickRaycast, GraphCollision.up, GraphCollision.fromHeight, GraphCollision.Raycast, GraphCollision.RaycastErrorMargin.
void Initialize(Matrix4x4 matrix, float scale)
Sets up several variables using the specified matrix and scale.
GraphCollision.up GraphCollision.upheight GraphCollision.finalRadius GraphCollision.finalRaycastRadius
References GraphCollision.up, GraphCollision.upheight, GraphCollision.height, GraphCollision.finalRadius, GraphCollision.diameter, GraphCollision.finalRaycastRadius, GraphCollision.thickRaycastDiameter.
Referenced by GridGraph.UpdateArea.
Vector3 Raycast(Vector3 origin, out RaycastHit hit, out bool walkable)
Same as CheckHeight, except that the raycast will always start exactly at origin walkable will be set to false if nothing was hit.
The ray will check a tiny bit further than to the grids base to avoid floating point errors when the ground is exactly at the base of the grid
References GraphCollision.heightCheck, GraphCollision.up, GraphCollision.fromHeight, GraphCollision.thickRaycast, GraphCollision.finalRaycastRadius, GraphCollision.heightMask, Mathfx.NearestPoint, GraphCollision.unwalkableWhenNoGround.
Referenced by GraphCollision.CheckHeightAll.