Pathfinding::GraphModifier
EventType
List<GraphModifier> activeModifiers
All active graph modifiers.
Referenced by GraphModifier.GetActiveModifiers, GraphModifier.OnEnable, GraphModifier.OnDisable.
int lastLateScanEvent
Last frame a late scan event was triggered.
Referenced by GraphModifier.TriggerEvent, GraphModifier.OnEnable.
int lastPostCacheEvent
Last frame a post cache event was triggered.
Referenced by GraphModifier.TriggerEvent, GraphModifier.OnEnable.
static List<GraphModifier> GetActiveModifiers()
Returns all active graph modifiers in the scene.
References GraphModifier.activeModifiers.
Referenced by GraphModifier.TriggerEvent.
static void TriggerEvent(GraphModifier.EventType type)
Triggers an event for all active graph modifiers.
References GraphModifier.GetActiveModifiers, GraphModifier.OnPreScan, GraphModifier.OnPostScan, GraphModifier.lastLateScanEvent, GraphModifier.OnLatePostScan, GraphModifier.OnGraphsPreUpdate, GraphModifier.OnGraphsPostUpdate, GraphModifier.lastPostCacheEvent, GraphModifier.OnPostCacheLoad.
Referenced by AstarPath.DoUpdateGraphs, AstarPath.ScanLoop.
virtual void OnDisable()
Removes this modifier from list of active modifiers.
References GraphModifier.activeModifiers.
virtual void OnEnable()
Adds this modifier to list of active modifiers.
Calls OnLatePostScan if the last late post scan event was triggered during this frame.
References GraphModifier.activeModifiers, GraphModifier.lastLateScanEvent, GraphModifier.OnLatePostScan, GraphModifier.lastPostCacheEvent, GraphModifier.OnPostCacheLoad.
virtual void OnGraphsPostUpdate()
Called after graphs have been updated using GraphUpdateObjects.
Eventual flood filling has been done
Referenced by GraphModifier.TriggerEvent.
virtual void OnGraphsPreUpdate()
Called before graphs are updated using GraphUpdateObjects.
Referenced by GraphModifier.TriggerEvent.
virtual void OnLatePostScan()
Called at the end of the scanning procedure.
This is the absolute last thing done by Scan.This event will be called even if Script Execution Order has messed things up (see the other two scan events).
Referenced by GraphModifier.TriggerEvent, GraphModifier.OnEnable.
virtual void OnPostCacheLoad()
Called after cached graphs have been loaded.
When using cached startup, this event is analogous to OnLatePostScan and implementing scripts should do roughly the same thing for both events.This event will be called even if Script Execution Order has messed things up (see the other two scan events).
Referenced by GraphModifier.TriggerEvent, GraphModifier.OnEnable.
virtual void OnPostScan()
Called right after all graphs have been scanned.
FloodFill and other post processing has not been done.Since OnEnable and Awake are called roughly in the same time, the only way to ensure that these scripts get this call when scanning in Awake is to set the Script Execution Order for AstarPath to some time later than default time (see Edit -> Project Settings -> Script Execution Order). OnLatePostScan
Referenced by GraphModifier.TriggerEvent.
virtual void OnPreScan()
Called right before graphs are going to be scanned.
Since OnEnable and Awake are called roughly in the same time, the only way to ensure that these scripts get this call when scanning in Awake is to set the Script Execution Order for AstarPath to some time later than default time (see Edit -> Project Settings -> Script Execution Order). OnLatePostScan
Referenced by GraphModifier.TriggerEvent.