GraphEditor
AstarPathEditor editor
void DrawCollisionEditor(GraphCollision collision)
Draws the inspector for a GraphCollision class .
References Separator, GraphCollision.collisionCheck, ToggleGroup, GraphCollision.type, GraphCollision.diameter, GraphCollision.height, GraphCollision.mask, GraphCollision.heightCheck, GraphCollision.fromHeight, GraphCollision.heightMask, GraphCollision.thickRaycast, GraphCollision.thickRaycastDiameter, GraphCollision.unwalkableWhenNoGround.
Referenced by GridGraphEditor.OnInspectorGUI.
bool FixLabel(string label, string buttonLabel="Fix", int buttonWidth=40)
Draws a small help box with a 'Fix' button to the right.
Boolean - Returns true if the button was clicked
Referenced by GridGraphEditor.ResourcesField, GridGraphEditor.DrawTextureData.
void HelpBox(string label)
Draws a small help box.
Works with EditorGUI.indentLevel
Referenced by GridGraphEditor.OnInspectorGUI, GridGraphEditor.DrawTextureData.
Object ObjectField(string label, Object obj, System.Type objType, bool allowSceneObjects)
Object ObjectField(GUIContent label, Object obj, System.Type objType, bool allowSceneObjects)
void OnBaseInspectorGUI(NavGraph target)
Draws common graph settings.
virtual void OnDestroy()
virtual void OnDisable()
virtual void OnDrawGizmos()
Override to implement scene Gizmos drawing for the graph editor.
virtual void OnEnable()
virtual void OnInspectorGUI(NavGraph target)
Override to implement graph inspectors.
virtual void OnSceneGUI(NavGraph target)
Override to implement scene GUI drawing for the graph.
void Separator()
Draws a thin separator line.
Referenced by DrawCollisionEditor, GridGraphEditor.OnInspectorGUI, RecastGraphEditor.OnInspectorGUI.
bool ToggleGroup(string label, bool value)
Draws a toggle with a bold label to the right.
Does not enable or disable GUI
Referenced by DrawCollisionEditor, GridGraphEditor.OnInspectorGUI, GridGraphEditor.DrawTextureData.
bool ToggleGroup(GUIContent label, bool value)
Draws a toggle with a bold label to the right.
Does not enable or disable GUI
static void DrawWireCube(Vector3 center, Vector3 size)
Draws a wire cube using handles.