Pathfinding::PointGraph
bool autoLinkNodes
Vector3 limits
Max distance along the axis for a connection to be valid.
0 = infinity
Referenced by PointGraphEditor.OnInspectorGUI, PointGraph.IsValidConnection.
LayerMask mask
Layer mask to use for raycast.
Referenced by PointGraphEditor.OnInspectorGUI, PointGraph.IsValidConnection.
float maxDistance
Max distance for a connection to be valid.
0 = infinity
Referenced by PointGraphEditor.OnInspectorGUI, PointGraph.IsValidConnection.
bool raycast
Use raycasts to check connections.
Referenced by PointGraphEditor.OnInspectorGUI, PointGraph.IsValidConnection.
bool recursive
Recursively search for childnodes to the root.
Referenced by PointGraphEditor.OnInspectorGUI, PointGraph.Scan.
Transform root
Childs of this transform are treated as nodes.
Referenced by PointGraphEditor.OnInspectorGUI, PointGraphEditor.OnDrawGizmos, PointGraph.Scan.
string searchTag
If no root is set, all nodes with the tag is used as nodes.
Referenced by PointGraphEditor.OnInspectorGUI, PointGraphEditor.OnDrawGizmos, PointGraph.Scan.
bool thickRaycast
Use thick raycast.
Referenced by PointGraphEditor.OnInspectorGUI, PointGraph.IsValidConnection, PointGraph.UpdateArea.
float thickRaycastRadius
Thick raycast radius.
Referenced by PointGraphEditor.OnInspectorGUI, PointGraph.IsValidConnection, PointGraph.UpdateArea.
GameObject [] nodeGameObjects
GameObjects which defined the node in the #nodes array.
Entries are permitted to be null in case no GameObject was used to define a node.
Referenced by PointGraph.AddChildren, PointGraph.Scan.
PointNode [] nodes
void AddChildren(ref int c, Transform tr)
Recursively adds childrens of a transform as nodes.
References PointGraph.nodeGameObjects.
Referenced by PointGraph.Scan.
override void GetNodes(GraphNodeDelegateCancelable del)
bool IsValidConnection(GraphNode a, GraphNode b, out float dist)
Returns if the connection between a and b is valid.
Checks for obstructions using raycasts (if enabled) and checks for height differences. As a bonus, it outputs the distance between the nodes too if the connection is valid
References PointGraph.limits, PointGraph.maxDistance, PointGraph.raycast, PointGraph.thickRaycast, PointGraph.thickRaycastRadius, PointGraph.mask.
Referenced by PointGraph.Scan, PointGraph.UpdateArea.
override void Scan()
Scans the graph, called from AstarPath.Scan Override this function to implement custom scanning logic
References PointGraph.root, PointGraph.searchTag, PointGraph.nodeGameObjects, NavGraph.CreateNodes, PointGraph.recursive, PointGraph.CountChildren, PointGraph.AddChildren, PointGraph.IsValidConnection, Int3.FloatPrecision.
void UpdateArea(GraphUpdateObject guo)
Updates an area in the list graph.
Recalculates possibly affected connections, i.e all connectionlines passing trough the bounds of the guo will be recalculated A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
References GraphUpdateObject.bounds, GraphUpdateObject.WillUpdateNode, GraphUpdateObject.Apply, GraphUpdateObject.updatePhysics, PointGraph.thickRaycast, PointGraph.thickRaycastRadius, Polygon.LineIntersectsBounds, GraphNode.ContainsConnection, PointGraph.IsValidConnection, Int3.FloatPrecision.
static int CountChildren(Transform tr)
Recursively counds children of a transform.
Referenced by PointGraph.Scan.