Pathfinding::NNConstraint
int area
Area ID to constrain to.
Will not affect anything if less than 0 (zero) or if constrainArea is false
Referenced by NNConstraint.Suitable, PathNNConstraint.SetStart.
bool constrainArea
Only treat nodes in the area area as suitable.
Does not affect anything if area is less than 0 (zero)
Referenced by NNConstraint.Suitable, PathNNConstraint.SetStart.
bool constrainDistance
Constrain distance to node.
Uses distance from AstarPath.maxNearestNodeDistance. If this is false, it will completely ignore the distance limit. This value is not used in this class, it is used by the AstarPath.GetNearest function.
Referenced by AstarPath.GetNearest, NavGraph.GetNearest, NavMeshGraph.GetNearestForceBoth.
bool constrainTags
Sets if tags should be constrained.
Referenced by NNConstraint.Suitable.
bool constrainWalkability
Only treat nodes with the walkable flag set to the same as walkable as suitable.
Referenced by NNConstraint.Suitable.
int graphMask
Graphs treated as valid to search on.
This is a bitmask meaning that bit 0 specifies whether or not the first graph in the graphs list should be able to be included in the search, bit 1 specifies whether or not the second graph should be included and so on. //Enablesthefirstandthirdgraphstobeincluded,butnottherest myNNConstraint.graphMask=(1<<0)|(1<<2); This does only affect which nodes are returned from a GetNearest call, if an invalid graph is linked to from a valid graph, it might be searched anyway. AstarPath.GetNearest
Referenced by Seeker.StartPath, NNConstraint.SuitableGraph.
int tags
Nodes which have any of these tags set are suitable.
This is a bitmask, i.e bit 0 indicates that tag 0 is good, bit 3 indicates tag 3 is good etc.
Referenced by NNConstraint.Suitable, ABPath.Prepare.
bool walkable
What must the walkable flag on a node be for it to be suitable.
Does not affect anything if constrainWalkability if false
Referenced by NNConstraint.Suitable.
NNConstraint Default
The default NNConstraint.
Equivalent to new NNConstraint (). This NNConstraint has settings which works for most, it only finds walkable nodes and it constrains distance set by A* Inspector -> Settings -> Max Nearest Node Distance
NNConstraint None
Returns a constraint which will not filter the results.
Referenced by AstarPath.GetNearest, NavGraph.GetNearest, GridGraph.SnappedLinecast, NavMeshGraph.Linecast.
NNConstraint()
Default constructor.
Equals to the property Default
virtual bool Suitable(GraphNode node)
Returns whether or not the node conforms to this NNConstraint's rules.
References NNConstraint.constrainWalkability, NNConstraint.walkable, NNConstraint.constrainArea, NNConstraint.area, NNConstraint.constrainTags, NNConstraint.tags.
Referenced by AstarPath.GetNearest, NavGraph.GetNearest, NavMeshGraph.GetNearestForceBoth.
virtual bool SuitableGraph(int graphIndex, NavGraph graph)
Returns whether or not the graph conforms to this NNConstraint's rules.
References NNConstraint.graphMask.
Referenced by AstarPath.GetNearest.