Pathfinding::PathHandler
const int BucketIndexMask
const int BucketSize
const int BucketSizeLog2
Log2 size of buckets.
So 10 yields a real bucket size of 1024. Be careful with large values.
BinaryHeapM heap
ushort pathID
ushort PathID
readonly System.Text.StringBuilder DebugStringBuilder
PathNode [][] nodes
PathHandler()
void ClearPathIDs()
Set all node's pathIDs to 0.
Pathfinding.PathNode.pathID
Referenced by Path.PrepareBase.
PathNode GetPathNode(GraphNode node)
PathNode GetPathNodeFast(GraphNode node)
Returns a NodeRun for a specified node.
Assumes everything is in place. Does not do any error checking at all. In other words, assumes GetPathNode has been called for the same node before this function is called.
bool HeapEmpty()
void InitializeForPath(Path p)
PathNode PopNode()
void PushNode(PathNode node)
void RebuildHeap()
PathNode TryGetPathNode(GraphNode node)
Tries to get a NodeRun for a node.
If there is none, returns null.Slightly slower than GetPathNodeFast. Will not allocate any new memory.
Referenced by NavGraph.InSearchTree, ABPath.DebugString.