Pathfinding::GridGraph
bool useRaycastNormal
Use heigh raycasting normal for max slope calculation.
True if maxSlope is less than 90 degrees.
Referenced by GridGraph.UpdateNodePositionCollision.
int width
Width of the grid in nodes.
Referenced by GridGraphEditor.OnInspectorGUI, GridGraphEditor.OnSceneGUI, GridGraph.CalculateConnections, GridGraph.OnPostScan, GridGraph.PostDeserialization.
int depth
Depth (height) of the grid in nodes.
Referenced by GridGraphEditor.OnInspectorGUI, GridGraphEditor.OnSceneGUI, GridGraph.OnPostScan, GridGraph.PostDeserialization.
float aspectRatio
Scaling of the graph along the X axis.
This should be used if you want different scales on the X and Y axis of the grid
Referenced by GridGraphEditor.OnInspectorGUI.
Vector3 rotation
Rotation of the grid in degrees.
Referenced by GridGraphEditor.OnInspectorGUI, GridGraphEditor.OnSceneGUI.
Bounds bounds
Vector3 center
Center point of the grid.
Referenced by GridGraphEditor.OnInspectorGUI, GridGraphEditor.OnSceneGUI.
Vector2 unclampedSize
Size of the grid.
Might be negative or smaller than nodeSize
Referenced by GridGraphEditor.OnInspectorGUI, GridGraphEditor.OnSceneGUI.
float nodeSize
Size of one node in world units.
Referenced by GridGraphEditor.OnInspectorGUI, GridGraphEditor.OnSceneGUI, GridGraph.UpdateArea, GridGraph.Linecast.
GraphCollision collision
Settings on how to check for walkability and height.
Referenced by GridGraphEditor.OnInspectorGUI, GridGraphEditor.DrawTextureData, GridGraph.UpdateNodePositionCollision, GridGraph.UpdateArea.
float maxClimb
The max position difference between two nodes to enable a connection.
Set to 0 to ignore the value.
Referenced by GridGraphEditor.OnInspectorGUI, GridGraph.IsValidConnection.
int maxClimbAxis
The axis to use for maxClimb.
X = 0, Y = 1, Z = 2.
Referenced by GridGraphEditor.OnInspectorGUI, GridGraph.IsValidConnection.
float maxSlope
The max slope in degrees for a node to be walkable.
Referenced by GridGraphEditor.OnInspectorGUI, GridGraph.UpdateNodePositionCollision.
int erodeIterations
Erosion of the graph.
The graph can be eroded after calculation. This means a margin is put around unwalkable nodes or other unwalkable connections. It is really good if your graph contains ledges where the nodes without erosion are walkable too close to the edge.Below is an image showing a graph with erode iterations 0, 1 and 2 <div class="tinyshadow"><img src="images/erosion.png"/></div>A high number of erode iterations can seriously slow down graph updates during runtime (GraphUpdateObject) and should be kept as low as possible. erosionUseTags
Referenced by GridGraphEditor.OnInspectorGUI, GridGraph.ErodeWalkableArea, GridGraph.UpdateArea.
bool erosionUseTags
Use tags instead of walkability for erosion.
Tags will be used for erosion instead of marking nodes as unwalkable. The nodes will be marked with tags in an increasing order starting with the tag erosionFirstTag. Debug with the Tags mode to see the effect. With this enabled you can in effect set how close different AIs are allowed to get to walls using the Valid Tags field on the Seeker component. <div class="tinyshadow"><img src="images/erosionTags.png"/></div> <div class="tinyshadow"><img src="images/erosionTags2.png"/></div> erosionFirstTag
Referenced by GridGraphEditor.OnInspectorGUI, GridGraph.ErodeWalkableArea.
int erosionFirstTag
Tag to start from when using tags for erosion.
erosionUseTags erodeIterations
Referenced by GridGraphEditor.OnInspectorGUI, GridGraph.ErodeWalkableArea.
bool autoLinkGrids
Auto link the graph's edge nodes together with other GridGraphs in the scene on Scan.
autoLinkDistLimit
Referenced by GridGraph.OnPostScan.
float autoLinkDistLimit
Distance limit for grid graphs to be auto linked.
autoLinkGrids
Referenced by GridGraph.OnPostScan.
NumNeighbours neighbours
Number of neighbours for each node.
Either four directional or eight directional
Referenced by GridGraphEditor.OnInspectorGUI, GridGraph.CalculateConnections, GridGraph.CheckConnection.
bool cutCorners
If disabled, will not cut corners on obstacles.
If connections is Eight, obstacle corners might be cut by a connection, setting this to false disables that.
Referenced by GridGraphEditor.OnInspectorGUI, GridGraph.CalculateConnections.
float penaltyPositionOffset
Offset for the position when calculating penalty.
penaltyPosition
Referenced by GridGraphEditor.OnInspectorGUI, GridGraph.UpdateNodePositionCollision.
bool penaltyPosition
Use position (y-coordinate) to calculate penalty.
Referenced by GridGraphEditor.OnInspectorGUI, GridGraph.UpdateNodePositionCollision.
float penaltyPositionFactor
Scale factor for penalty when calculating from position.
penaltyPosition
Referenced by GridGraphEditor.OnInspectorGUI, GridGraph.UpdateNodePositionCollision.
bool penaltyAngle
float penaltyAngleFactor
TextureData textureData
Holds settings for using a texture as source for a grid graph.
Texure data can be used for fine grained control over how the graph will look. It can be used for positioning, penalty and walkability control. Below is a screenshot of a grid graph with a penalty map applied. It has the effect of the AI taking the longer path along the green (low penalty) areas. <div class="tinyshadow"><img src="images/penaltymap.png"/></div> Color data is got as 0...255 values. A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here Can only be used with Unity 3.4 and up
Referenced by GridGraphEditor.OnInspectorGUI.
int Depth
virtual bool uniformWidhtDepthGrid
This is placed here so generators inheriting from this one can override it and set it to false.
If it is true, it means that the nodes array's length will always be equal to width*depth It is used mainly in the editor to do auto-scanning calls, setting it to false for a non-uniform grid will reduce the number of scans
Referenced by GridGraphEditor.OnSceneGUI.
int Width
Matrix4x4 boundsMatrix
Matrix4x4 boundsMatrix2
int getNearestForceOverlap
In GetNearestForce, determines how far to search after a valid node has been found.
readonly uint [] neighbourCosts
Costs to neighbour nodes.
readonly int [] neighbourOffsets
Index offset to get neighbour nodes.
Added to a node's index to get a neighbour node index
Referenced by GridGraph.GetNodeConnection, GridGraph.CalculateConnections, GridGraph.SnappedLinecast, GridGraph.CheckConnection.
readonly int [] neighbourXOffsets
Offsets in the X direction for neighbour nodes.
Only 1, 0 or -1
Referenced by GridGraph.GetNodeConnection, GridGraph.CalculateConnections.
readonly int [] neighbourZOffsets
Offsets in the Z direction for neighbour nodes.
Only 1, 0 or -1
Referenced by GridGraph.GetNodeConnection, GridGraph.CalculateConnections.
GridNode [] nodes
int scans
Vector2 size
Size of the grid.
Will always be positive and larger than nodeSize.GenerateMatrix
int [] corners
To reduce memory allocations this array is reused.
Used in the CalculateConnections function CalculateConnections
Referenced by GridGraph.CalculateConnections.
GridGraph()
void AddPortal(GraphNode n1, GraphNode n2, List< Vector3 > left, List< Vector3 > right)
Add the portal between node n1 and n2 to the funnel corridor.
The left and right edges does not necesarily need to be the left and right edges (right can be left), they will be swapped if that is detected. But that works only as long as the edges do not switch between left and right in the middle of the path.
void AddPortal(GridNode n1, GridNode n2, List< Vector3 > left, List< Vector3 > right)
void BuildFunnelCorridor(List< GraphNode > path, int sIndex, int eIndex, List< Vector3 > left, List< Vector3 > right)
virtual void CalculateConnections(GridNode[] nodes, int x, int z, GridNode node)
Calculates the grid connections for a single node.
References GridGraph.corners, GridGraph.neighbourXOffsets, GridGraph.neighbourZOffsets, GridGraph.neighbourOffsets, GridGraph.IsValidConnection, GridGraph.neighbours, GridGraph.cutCorners.
bool CheckConnection(GridNode node, int dir)
Returns if node is connected to it's neighbour in the specified direction.
This will also return true if neighbours = NumNeighbours.Four, the direction is diagonal and one can move through one of the adjacent nodes to the targeted node.
References GridGraph.neighbours, GridGraph.neighbourOffsets.
Referenced by GridGraph.SnappedLinecast.
override void CreateNodes(int number)
Creates a number of nodes with the correct type for the graph.
This should not set the #nodes array, only return the nodes. Called by graph generators and when deserializing a graph with nodes. Override this function if you do not use the default Pathfinding.Node class.
virtual void ErodeWalkableArea()
Erodes the walkable area.
erodeIterations
Referenced by GridGraph.UpdateArea.
virtual void ErodeWalkableArea(int xmin, int zmin, int xmax, int zmax)
Erodes the walkable area.
xmin, zmin (inclusive) xmax, zmax (exclusive)erodeIterations
References GridGraph.erosionUseTags, GridGraph.erodeIterations, GridGraph.CalculateConnections, GridGraph.erosionFirstTag.
void GenerateMatrix()
Generates the matrix used for translating nodes from grid coordinates to world coordintes.
Referenced by GridGraphEditor.OnInspectorGUI, GridGraphEditor.OnSceneGUI, GridGraph.PostDeserialization.
void GetBoundsMinMax(Bounds b, Matrix4x4 matrix, out Vector3 min, out Vector3 max)
Calculates minimum and maximum points for bounds b when multiplied with the matrix.
Referenced by GridGraph.GetNodesInArea, GridGraph.UpdateArea.
uint GetConnectionCost(int dir)
override NNInfo GetNearest(Vector3 position, NNConstraint constraint, GraphNode hint)
TodoSet clamped position for Grid Graph
Referenced by GridGraphEditor.OnSceneGUI, GridGraph.OnPostScan, GridGraph.SnappedLinecast.
override NNInfo GetNearestForce(Vector3 position, NNConstraint constraint)
TodoSet clamped position for Grid Graph
GridNode GetNodeConnection(GridNode node, int dir)
GridNode GetNodeConnection(int index, int x, int z, int dir)
Get the connecting node from the node at (x,z) in the specified direction.
A GridNode if the node has a connection to that node. Null if no connection in that direction exists GridNode
References GridGraph.neighbourXOffsets, GridGraph.neighbourZOffsets, GridGraph.neighbourOffsets.
Int3 GetNodePosition(int index, int yOffset)
override void GetNodes(GraphNodeDelegateCancelable del)
List<GraphNode> GetNodesInArea(Bounds b)
All nodes inside the bounding box.
Be nice to the garbage collector and release the list when you have used it (optional) Pathfinding.Util.ListPoolGetNodesInArea(GraphUpdateShape)
Referenced by GridGraph.GetNodesInArea.
List<GraphNode> GetNodesInArea(GraphUpdateShape shape)
All nodes inside the shape.
Be nice to the garbage collector and release the list when you have used it (optional) Pathfinding.Util.ListPoolGetNodesInArea(Bounds)
References GridGraph.GetNodesInArea.
bool HasNodeConnection(GridNode node, int dir)
bool HasNodeConnection(int index, int x, int z, int dir)
virtual bool IsValidConnection(GridNode n1, GridNode n2)
Returns true if a connection between the adjacent nodes n1 and n2 is valid.
Also takes into account if the nodes are walkable
References GridGraph.maxClimb, GridNode.Position, GridGraph.maxClimbAxis, Int3.Precision.
Referenced by GridGraph.CalculateConnections.
bool Linecast(Vector3 _a, Vector3 _b)
Returns if _b is visible from _a on the graph.
This is not the same as Physics.Linecast, this function traverses the graph and looks for collisions. A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
Referenced by GridGraph.Linecast.
bool Linecast(Vector3 _a, Vector3 _b, GraphNode hint)
Returns if _b is visible from _a on the graph.
_a Point to linecast from _b Point to linecast to hint If you have some idea of what the start node might be (the one close to _a), pass it to hint since it can enable faster lookups This is not the same as Physics.Linecast, this function traverses the graph and looks for collisions. A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
References GridGraph.Linecast.
bool Linecast(Vector3 _a, Vector3 _b, GraphNode hint, out GraphHitInfo hit)
Returns if _b is visible from _a on the graph.
_a Point to linecast from _b Point to linecast to hit Contains info on what was hit, see GraphHitInfo hint If you have some idea of what the start node might be (the one close to _a), pass it to hint since it can enable faster lookups This is not the same as Physics.Linecast, this function traverses the graph and looks for collisions. A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
References Polygon.SegmentIntersectionPoint, Polygon.Left, GridGraph.nodeSize, NavGraph.matrix.
override void OnDestroy()
This function will be called when this graph is destroyed.
override void OnDrawGizmos(bool drawNodes)
void OnPostScan(AstarPath script)
Auto links grid graphs together.
Called after all graphs have been scanned. autoLinkGrids
References AstarPath.OnPostScan, GridGraph.autoLinkGrids, GridGraph.autoLinkDistLimit, Int3.Precision, GridGraph.width, GridGraph.GetNearest, NNInfo.node, GridGraph.depth.
override void PostDeserialization()
Called after all deserialization has been done for all graphs.
Can be used to set up more graph data which is not serialized
References GridGraph.GenerateMatrix, GridGraph.SetUpOffsetsAndCosts, AstarPath.active, AstarPath.astarData, GridGraph.depth, GridGraph.width.
void RemoveGridGraphFromStatic()
override void Scan()
Scans the graph, called from AstarPath.Scan Override this function to implement custom scanning logic
void SetNodeConnection(GridNode node, int dir, bool value)
void SetNodeConnection(int index, int x, int z, int dir, bool value)
Set if connection in the specified direction should be enabled.
Note that bounds checking will still be done when getting the connection value again, so it is not necessarily true that HasNodeConnection will return true just because you used SetNodeConnection on a node to set a connection to true. index Index of the node x X coordinate of the node z Z coordinate of the node value Enable or disable the connection This is identical to Pathfinding.Node.SetConnectionInternal Deprecated
virtual void SetUpOffsetsAndCosts()
Sets up neighbourOffsets with the current settings.
neighbourOffsets, neighbourCosts, neighbourXOffsets and neighbourZOffsets are set up. The cost for a non-diagonal movement between two adjacent nodes is RoundToInt (nodeSize * Int3.Precision) The cost for a diagonal movement between two adjacent nodes is RoundToInt (nodeSize * Sqrt (2) * Int3.Precision)
Referenced by GridGraph.PostDeserialization.
bool SnappedLinecast(Vector3 _a, Vector3 _b, GraphNode hint, out GraphHitInfo hit)
Returns if _b is visible from _a on the graph.
This function is different from the other Linecast functions since it 1) snaps the start and end positions directly to the graph and it uses Bresenham's line drawing algorithm as opposed to the others which use sampling at fixed intervals. If you only care about if one node can see another node, then this function is great, but if you need more precision than one node, use the normal linecast functions _a Point to linecast from _b Point to linecast to hit Contains info on what was hit, see GraphHitInfo hint If you have some idea of what the start node might be (the one close to _a), pass it to hint since it can enable faster lookups This is not the same as Physics.Linecast, this function traverses the graph and looks for collisions. A* Pro Feature: This is an A* Pathfinding Project Pro feature only. This function/class/variable might not exist in the Free version of the A* Pathfinding Project or the functionality might be limited The Pro version can be bought here
References GridGraph.GetNearest, NNConstraint.None, NNInfo.node, NavGraph.matrix, GridGraph.neighbourOffsets, GridGraph.CheckConnection.
void UpdateArea(GraphUpdateObject o)
Internal function to update an area of the graph.
References GraphUpdateObject.bounds, GridGraph.GetBoundsMinMax, NavGraph.matrix, IntRect.DebugDraw, GraphUpdateObject.updatePhysics, GraphUpdateObject.modifyWalkability, GridGraph.collision, GraphCollision.collisionCheck, GraphCollision.diameter, IntRect.Union, GridGraph.erodeIterations, IntRect.Expand, IntRect.Intersection, GraphUpdateObject.WillUpdateNode, GraphCollision.Initialize, GridGraph.nodeSize, GridGraph.UpdateNodePositionCollision, GraphUpdateObject.Apply, GridGraph.CalculateConnections, GridNode.Position, GridGraph.ErodeWalkableArea.
void UpdateNodePositionCollision(GridNode node, int x, int z)
Updates position, walkability and penalty for the node.
Assumes that collision.Initialize (...) has been called before this function
References GridNode.YOffset, GridGraph.collision, GraphCollision.CheckHeight, GridNode.Position, GraphCollision.fromHeight, Int3.Precision, GridGraph.penaltyPosition, GridGraph.penaltyPositionOffset, GridGraph.penaltyPositionFactor, GridGraph.useRaycastNormal, GraphCollision.heightCheck, GraphCollision.up, GridGraph.maxSlope, GraphCollision.Check.
Referenced by GridGraph.UpdateArea.
void UpdateSizeFromWidthDepth()
Updates size from width, depth and nodeSize values.
Also generates a new matrix . This does not rescan the graph, that must be done with Scan
static void CalculateConnections(GridNode node)
Calculates the grid connections for a single node.
Convenience function, it's faster to use CalculateConnections(GridNode[],int,int,node) but that will only show when calculating for a large number of nodes TodoTest this function, should work ok, but you never know
References AstarData.GetGraph, GridGraph.width, GridGraph.CalculateConnections.
Referenced by GridGraph.ErodeWalkableArea, GridGraph.CalculateConnections, GridGraph.UpdateArea.
List<GraphNode> GetNodesInArea(Bounds b, GraphUpdateShape shape)
All nodes inside the shape or if null, the bounding box.
If a shape is supplied, it is assumed to be contained inside the bounding box. GraphUpdateShape.GetBounds
References GridGraph.GetBoundsMinMax, IntRect.Intersection.