Pathfinding::GraphNode
int NextNodeIndex
const uint FlagsGraphMask
const int FlagsGraphOffset
const uint FlagsRegionMask
const int FlagsRegionOffset
const uint FlagsTagMask
const int FlagsTagOffset
const uint FlagsWalkableMask
const int FlagsWalkableOffset
readonly int nodeIndex
uint penalty
uint flags
Penlty cost for walking on this node.
This can be used to make it harder/slower to walk over certain areas.
uint Flags
Penlty cost for walking on this node.
This can be used to make it harder/slower to walk over certain areas.
Referenced by GraphUpdateObject.WillUpdateNode.
uint GraphIndex
int NodeIndex
uint Penalty
abstract Int3 Position
uint Region
uint Tag
bool Walkable
GraphNode()
virtual bool ContainsConnection(GraphNode node)
Checks if this node has a connection to the specified node.
Referenced by PointNode.Open, TriangleMeshNode.Open, ConvexMeshNode.Open, PointGraph.UpdateArea.
virtual void FloodFill(Stack< GraphNode > stack, uint region)
abstract void GetConnections(GraphNodeDelegate del)
Calls the delegate with all connections from this node.
virtual void GetPortal(GraphNode other, List< Int3 > left, List< Int3 > right, bool backwards)
Add a portal from this node to the specified node.
abstract void Open(Path path, PathNode pathNode, PathHandler handler)
Open the node.
Referenced by ABPath.Initialize, ABPath.CalculateStep.
virtual void RecalculateConnectionCosts()
Recalculates all connection costs from this node.
Depending on the node type, this may or may not be supported. Nothing will be done if the operation is not supported TodoUse interface?
void UpdateG(Path path, PathNode pathNode)
virtual void UpdateRecursiveG(Path path, PathNode pathNode, PathHandler handler)