Pathfinding::IntRect
int xmax
int xmin
int ymax
int ymin
IntRect(int xmin, int ymin, int xmax, int ymax)
bool Contains(int x, int y)
void DebugDraw(Matrix4x4 matrix, Color col)
Draws some debug lines representing the rect.
Referenced by GridGraph.UpdateArea.
IntRect Expand(int range)
Returns a new rect which is expanded by range in all directions.
range How far to expand. Negative values are permitted.
Referenced by GridGraph.UpdateArea.
bool IsValid()
Returns if this rectangle is valid.
An invalid rect could have e.g xmin > xmax
static IntRect Intersection(IntRect a, IntRect b)
Returns the intersection rect between the two rects.
The intersection rect is the area which is inside both rects. If the rects do not have an intersection, an invalid rect is returned. IsValid
Referenced by GridGraph.GetNodesInArea, GridGraph.UpdateArea.
static IntRect Union(IntRect a, IntRect b)
Returns a new rect which contains both input rects.
This rectangle may contain areas outside both input rects as well in some cases.
Referenced by GridGraph.UpdateArea.